### ISSUE TITLE
Navigating back to panel section of panel config silently crashes when name is empty

### ISSUE THREAD

**Issue by esensar** [nwg-piotr/nwg-panel#10]
![image](https://user-images.githubusercontent.com/2764831/108264087-641b1a00-7167-11eb-94c8-f54d719c32bb.png)
When returning back to **Panel** section of panel configuration window, configuration silently crashes:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/nwg_panel/config.py", line 510, in edit_panel
    self.eb_name.set_text(self.panel["name"])
KeyError: 'name'
```

Adding a name and then applying it resolves this issue.

I just quickly checked out the file, but I couldn't find the issue. I will try to make a PR if I find a solution.

**Comment by esensar** [comment]
Issue seems to be in `load_panel()`. It leaves panel without a `name` value, since it is empty. When editor is initialized, `set_panel()` is called, which fills out defaults. When replacing `load_panel()` call found on every button action with `set_panel()` it seems to be working fine, but I am not sure if this is the right solution.

**Comment by nwg-piotr** [comment]
Well, I couldn't reproduce the issue in real life, but removal of the `"output": ""` value manually from the config file allowed me to see the crash. I separated the defaults check into another method, and call it from inside `edit_panel` just in case. This should fix the issue. Thank you for reporting it.
