### ISSUE TITLE
module sway-taskbar: why is there an a before the workspace number?

### ISSUE THREAD

**Issue by japhir** [nwg-piotr/nwg-panel#100]
**Is your feature request related to a problem? Please describe.**
I've just configured everything to my liking, using sway-taskbar to show the currently active apps. However, I don't understand why it shows an a before each workspace name:

![2022-04-05-11:38:22_region](https://user-images.githubusercontent.com/10659193/161725710-c5c94c88-9a70-47d1-b303-52c275ff233d.png)

**Describe the solution you'd like**
I'd prefer to only show the workspace number, or perhaps even the option to hide it because I always open the same apps on the same workspace.

**Describe alternatives you've considered**
I could perhaps make the css of the foreground say it's transparent? But then it would still have the padding?

Anyway, great work here, I've just switched from using waybar to this, and it's been pretty easy to get everything looking the way I'd like except *fancy*. ♥

**Comment by nwg-piotr** [comment]
It marks workspaces with autotiling turned on. If you use autotiling on all workspaces, make sure you start it w/o the `-w` argument, and remove `/tmp/autotiling` file.

I should add a switch in the panel config to turn the "a" marker on/off. I will.

**Comment by japhir** [comment]
Great, this resolves the issue for me! Feel free to close the issue or leave it open if you want a reminder for someday writing an a marker on/off switch.

**Comment by nwg-piotr** [comment]
I'll leave it open. The whole project gets too big for me to remember each TODO. :)
