### ISSUE TITLE
Formattable clock tooltip

### ISSUE THREAD

**Issue by ChrRubin** [nwg-piotr/nwg-panel#104]
**Is your feature request related to a problem? Please describe.**
It'd be nice to be able to have a formattable tooltip for the clock module instead of a static tooltip text so we can have a simple clock shown on the panel and a more detailed date/time string when hovering over the clock.

**Describe the solution you'd like**
Allow using `date` format sequences for tooltips on the clock module.

**Describe alternatives you've considered**
Add the ability have "dynamic" tooltips that would run a command and use its output as the tooltip text when the tooltip is shown. This might also be useful for other modules.

**Additional context**
None.

**Comment by nwg-piotr** [comment]
You mean something like this?

![image](https://user-images.githubusercontent.com/20579136/163490086-e6165f53-667a-4127-bf7c-01050e195f18.png)

Sure, why not?
