### ISSUE TITLE
[BUG] sway-taskbar isn't responsive on second monitor, after sometime the panel dissappears

### ISSUE THREAD

**Issue by japhir** [nwg-piotr/nwg-panel#106]
**Describe the bug**
Since switching about a week ago, there's a weird bug that creeps up every now and then (like 1/3 of days that I log in). It's kind of hard to reproduce: sway-taskbar isn't responsive on second monitor, after sometime the panel dissappears

**To Reproduce**
1. modify preset-1 to have sway-taskbar as modules-left entry and to display the top panel on All displays
2. log in/reload (note that somehow firefox gets trashed when I refresh sway! :O)
3. often on login, the sway-taskbar module doesn't update correctly; it doesn't generate new workspace name labels or icons for newly launched apps
4. at some point, after using the system for a while, the panel disappears from the secondary monitor. It keeps working on primary.

**Expected behavior**
I'd expect sway-taskbar to update correctly, and for the panel on the external monitor to remain present

**Desktop (please complete the following information):**
 - Arch Linux
 - sway version 1.7
 - Panel version 0.6.3

**Comment by nwg-piotr** [comment]
Well, couldn't confirm on my 3-headed setup. One suspicion: do you by any chance use displays of different widths? If so, I'd recommend not to use 'Output' = 'All' but define a panel for each output separately. One way or another those are always separate instances.

**Comment by nwg-piotr** [comment]
Closing due to no further input.
