### ISSUE TITLE
[BUG] Some icons not showing in SwayTaskbar/Scratchpad

### ISSUE THREAD

**Issue by ChrRubin** [nwg-piotr/nwg-panel#107]
**Describe the bug**
Two of my applications' icons are not being loaded in SwayTaskbar and Scratchpad modules. They are `visual-studio-code-bin` and `input-remapper-git` installed from AUR.

**To Reproduce**
1. Launch the application(s) with SwayTaskbar module enabled, or send the application(s) to scratchpad with Scratchpad module enabled.

**Expected behavior**
Icons show up as expected.

**Screenshots**
Here's what it looks like in SwayTaskbar. I've included a snippet of the `.desktop` files of the applications from `/usr/share/applications`.

![image](https://user-images.githubusercontent.com/20059164/164615943-dbc18bfd-5683-4c3d-a447-f999dc0ee9f2.png)

**Desktop (please complete the following information):**
 - Distro: Arch Linux 5.17.3-arch1-1
 - Sway version: 1.7
 - Panel version: 0.6.3

**Additional context**
There are no overrides of the `.desktop` files in `~/.local/share/applications`.

Loading both icons in CustomButton works as expected:

![image](https://user-images.githubusercontent.com/20059164/164616789-99a6e270-211b-4d25-9378-9bc3e546da18.png)

![image](https://user-images.githubusercontent.com/20059164/164616840-e77d83fe-e929-4221-b164-f57632bcd058.png)

![image](https://user-images.githubusercontent.com/20059164/164616895-c102fe4a-eeec-4f87-b1c2-e8686b8fea92.png)

**Comment by nwg-piotr** [comment]
Well, after checking the tree, what we know about the VS Code task is:

```
"name": "Get Started - Visual Studio Code",
"window": 4194307,
"nodes": [
],
"floating_nodes": [
],
"focus": [
],
"fullscreen_mode": 0,
"sticky": false,
"pid": 77446,
"app_id": null,
"visible": true,
"max_render_time": 0,
"shell": "xwayland",
"inhibit_idle": false,
"idle_inhibitors": {
"user": "none",
"application": "none"
},
"window_properties": {
"class": "Code",
"instance": "code",
"title": "Get Started - Visual Studio Code",
"transient_for": null,
"window_role": "browser-window",
"window_type": "normal"
}
```

The SwayTaskbar module reads the sway tree to find active tasks. For VS Code the `app_id` is `null`, and the window class is `Code`. We can find the icon name either by the `app_id` or by reading the .desktop file, which should be named after the window class. See [this](https://github.com/nwg-piotr/nwg-panel/blob/b0e97bd50471c98bb7d4ec4666dcd13888e1f32a/nwg_panel/tools.py#L106).

**This is the application's fault**. I recommend to use [Code OSS](https://archlinux.org/packages/community/x86_64/code), which behaves properly: `"class": "code-oss"`, and the desktop file name is `code-oss.desktop`.

Alternatively, you can copy `visual-studio-code.desktop` to `~/local/share/applications/` and rename it to `code.desktop`. Don't forget to add `NoDisplay=true` in the `[Desktop Entry]` section, or you'll have a duplicated antry in launchers.

Dunno about the `input-remapper-git` app. I don't run unknown apps that demand sudo privileges before they even start. :) Probably a similar issue.

**Comment by ChrRubin** [comment]
Ah I see. `input-remapper-git` has an app_id of `input-remapper-gtk`, so that makes sense. I'll just copy the desktop files and rename them then.

Thanks for the clarification.
