### ISSUE TITLE
Not able to run on Wayfire 

### ISSUE THREAD

**Issue by th3cr00k3dm4n** [nwg-piotr/nwg-panel#108]
`Couldn't load system tray, is 'python-dasbus' installed?
Dependencies check: {'light': False, 'brightnessctl': True, 'pamixer': False, 'pactl': True, 'playerctl': True, 'netifaces': False, 'btmgmt': True, 'wlr-randr': False, 'upower': True, 'swaync': False}
Running on Wayland, but not sway
'wlr-randr' command not found, terminating`

**Comment by nwg-piotr** [comment]
1. read Wiki -> [Installation](https://github.com/nwg-piotr/nwg-panel/wiki/Installation)
2. install 'python-dasbus'
3. install 'python-netifaces'
4. install 'wlr-randr'
