### ISSUE TITLE
[BUG] Install just creates a `nwg-wrapper` executable and not `nwg-panel`

### ISSUE THREAD

**Issue by felixmr1** [nwg-piotr/nwg-panel#114]
Is the wiki depricated? The nwg-wrapper seems to differ quite alot from `nwg-panel` :thinking:

**Comment by nwg-piotr** [comment]
Copy-paste from [Wiki](https://github.com/nwg-piotr/nwg-panel/wiki/Installation):

```
git clone https://github.com/nwg-piotr/nwg-panel.git
cd nwg-panel
sudo ./install.sh
```
