### ISSUE TITLE
Weird X in name for some apps? 

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-panel#116]
The device I use nwg on has been dormant for a few months and all i've done is keep it updated so this may not be a problem but just a new feature I dont understand, but there is an " X | " before a few of my applications in the bottom bar. I attached an image, if this is intended behavior my apologies but I just noticed it doesnt happen with all apps. Any help is greatly appreciated.

Thanks for such a great suite of utilities so far have loved every bit of it. 

![image](https://user-images.githubusercontent.com/84921777/171759616-1e56a738-d9f2-4c92-a4da-bd380e26bb0e.png)

**Comment by nwg-piotr** [comment]
This is to tell you that this task is running under XWayland. You may turn it on/off in the SwayTaskbar settings:

![image](https://user-images.githubusercontent.com/20579136/171759987-2f85ab1c-ce80-4570-a26f-175fa0aae32c.png)

**Comment by xi-pinmping** [comment]
Ah that makes sense I hadnt noticed that in the new update sorry, thanks for such a timely response this man hot on the draw. 
Keep up the great work!
