### ISSUE TITLE
Controlling brightness for external monitors using ddcutil

### ISSUE THREAD

**Issue by az01101001** [nwg-piotr/nwg-panel#118]
**Is your feature request related to a problem? Please describe.**

As a desktop PC user, I use `ddcutil` instead of `light` or `brightnessctl` to control my display brightness.

**Describe the solution you'd like**

To be able to use the current brightness slider in the controls module to control brightness for external displays.

**Describe alternatives you've considered**

Other than that, I also propose to allow users to choose between `light`, `brightnessctl` and `ddcutil` in the settings, since the current logic automatically chooses by the order of met dependency (`light`, then `brightnessctl`, etc.).
This would be useful for users who have more than one of the dependencies installed, for example laptop users who also use additional external monitors.

**Additional context**

**Comment by az01101001** [comment]
I have created a pull request here: #119

**Comment by nwg-piotr** [comment]
I've been working on the OpenWeather module on the other branch. It's almost ready on the module side, but still misses the config. Adding it will take me one or two days more. Will you be rady to rebase your PRs, when I merge the `ow` branch?

**Comment by az01101001** [comment]
Sure thing. I'm still learning the ropes so please bear with me, but from the looks of it there's not much overlaps. Is it a good idea to do a rebase from the `ow` branch now, or is it better to wait for it be finalized and merged first?

**Comment by nwg-piotr** [comment]
Well, the frontend misses multi-language support (a minor thing), and I need to add some config form and code. It's 4:37 in my place, so time to go to bed. I hope to be ready tomorrow, or no later than Monday.

**Comment by az01101001** [comment]
Alright then. I'll try to look into it to familiarize myself more with the codebase.

**Comment by nwg-piotr** [comment]
Sorry for the delay. It always takes twice as much time as one expects.

My code on the `ow` seems to be ready. I'll spend several hours on testing and hopefully merge the branch tonight (before midnight CET).

**Comment by nwg-piotr** [comment]
Ready.

**Comment by az01101001** [comment]
Ok I've rebased and force-pushed all of them. There were no conflicts, and didn't encounter any errors while testing either. Hope I did things correctly.

**Comment by nwg-piotr** [comment]
Very well. I'll take a closer look at your work tonight.

**Comment by az01101001** [comment]
Thanks. Appreciate it if you have any feedback

**Comment by az01101001** [comment]
#119 and #130
