### ISSUE TITLE
Separate horizontal and vertical margin for controls module popup window

### ISSUE THREAD

**Issue by az01101001** [nwg-piotr/nwg-panel#120]
**Is your feature request related to a problem? Please describe.**

When setting a small width (or setting horizontal padding) on a panel alongside the controls module, the popup window will always stick to the edge of the display. The current option affects both the horizontal and vertical margins at once, so the when trying to adjust the popup window to follow the panel, it will move to the center of the screen instead of shifting in only one axis.

**Describe the solution you'd like**

To be able to set the horizontal and vertical margins separately. In my case, I want to be able to just set my controls horizontal margin equal to my panel horizontal padding, while leaving controls vertical margin to 0.

**Describe alternatives you've considered**

The margin value should be applied according to the side where the controls module is placed.
For example:
- panel: top
- controls: right
- horizontal popup margin starts from right edge
- vertical popup margin starts from top edge

It would also not hurt to extend the range to negative values as well, as it would allow finer control of the position of the popup window.

**Additional context**

**Comment by nwg-piotr** [comment]
merged
