### ISSUE TITLE
Custom labels for workspaces

### ISSUE THREAD

**Issue by az01101001** [nwg-piotr/nwg-panel#122]
**Is your feature request related to a problem? Please describe.**

I wanted to use dots (○ and ●, etc.) for the workspace buttons, instead  of just using the default numbers.
I've also seen people use kanji numbers or even labels like `www` and `dev` in their ricing, so this could also be useful to them.
It would also be nice to be able to have custom labels for focused workspaces as well, for example `●` for focused workspace and `○` for the rest.

**Describe the solution you'd like**

Add options for `custom labels` and `focused labels`, similar to the current method of choosing workspace `numbers`.
There should be a check to ensure that the number of `custom labels` given is the same with the number of chosen workspace `numbers`. Then we can just simply map each workspace number to their corresponding custom label.
When only one custom label is provided, it can be assumed that the user wants to use the same label across all workspace.

**Describe alternatives you've considered**

I am aware that Sway allows custom workspace names, but even they suggest to use numbers instead of names to allow easy switching of workspaces using keybinds.
This would be an easier way to use labels or names for workspaces without breaking Sway, as even Waybar doesn't support this.

**Additional context**

**Comment by nwg-piotr** [comment]
merged
