### ISSUE TITLE
TaskBar widgets,  missing style information for workspace/workspace bars

### ISSUE THREAD

**Issue by ackstorm23** [nwg-piotr/nwg-panel#126]
**Is your feature request related to a problem? Please describe.**

I can't seem to find a way to style the taskbar workspace/workspace buttons.    In fact all I seem to be able to style are the window boxes.    

Am I missing something?

**Describe the solution you'd like**

The ability to style the TaskBar widget's workspace/workspace buttons via style.css

**Describe alternatives you've considered**

I've considered using a different bar :)

**Additional context**

Am I missing something?

**Comment by nwg-piotr** [comment]
Well, I didn't expect someone would like to give them a separate styling. Couldn't you just adjust the `button` style to your needs?

```css
button {
    margin: 2px;
    background: none;
    border: none
}
```

**Comment by ackstorm23** [comment]
You are absolutely right, somehow when I tried that I must have had a syntax error. 

I've tried it now and it works great.

**Comment by nwg-piotr** [comment]
Thank God. I'm useless at css. ;)
