### ISSUE TITLE
Add an option to open menus on click only (not on hover)

### ISSUE THREAD

**Issue by tukusejssirs** [nwg-piotr/nwg-panel#133]
**Is your feature request related to a problem? Please describe.**

I’d like to disable menu (any menu, even custom) opening on hover.

**Describe the solution you'd like**

On hover, I’d like to see a tooltip (simple, configurable message), on left-click open the default action, on right-click open another action. An action could be opening a menu or execution of a script/program.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by nwg-piotr** [comment]
Which "menu" do you mean? If Controls, uncheck this:

![image](https://user-images.githubusercontent.com/20579136/179113862-3daa2418-134d-46a0-9d66-c72b6f442985.png)
