### ISSUE TITLE
[BUG] only half the panel shown on scaled output (HiDPI / 4K)

### ISSUE THREAD

**Issue by simonvanderveldt** [nwg-piotr/nwg-panel#134]
Hi! First of all thanks for the awesome project! Been trying it out together with Wayfire and it's been the closest to a DE feeling WM (without the bloat ;)) experience so far :+1: 

**Describe the bug**
I'm using 4K monitors that I either scale to 150 or 200%. I'll use the 200% case for the example.
When using 200% scale I can only see the left half of the panel :)
Note that I'm using Wayfire, scaling is configured like this in `~/.config/wayfire.ini`:
```
[output]
scale = 2.000000
```
Not sure if this is a generic problem or maybe it would work with Sway? I've never used Sway so don't have any experience with it. If it would help I can try to setup Sway and test it there.

**To Reproduce**
1. Set scaling to 200%
2. (Re)start WM
3. Only see the left half of the panel

**Expected behavior**
Entire panel is shown and scaled correctly

**Desktop (please complete the following information):**
 - Gentoo
 - Wayfire 0.7.3
 - 0.7.2

P.S. Could also be a feature request for scale/HiDPI support I guess :)

**Comment by nwg-piotr** [comment]
Have you tried unchecking "Auto" and entering the panel width manually?

![image](https://user-images.githubusercontent.com/20579136/180604175-200016c5-e2c2-41b4-a7b7-df8b88519f0f.png)

**Comment by simonvanderveldt** [comment]
That does seem to work. Shouldn't the panel be able to figure the with out itself though when set to auto?

Before
![scale-2-half-panel](https://user-images.githubusercontent.com/204286/180620527-ae6128f0-0880-46cd-af2d-6b2656a08225.png)

After
![scale-2-fixed-width-panel](https://user-images.githubusercontent.com/204286/180620548-fd29ebe6-8e44-4f45-8cd0-47f9dd71d8f3.png)

**Comment by nwg-piotr** [comment]
I only take in consideration the screen dimensions returned by the sway ipc, but not scaling. I only have 3 x 1920x1080 displays, and no 4K output to test on it.

**Comment by nwg-piotr** [comment]
Should be all right now.

**Comment by Sivecano** [comment]
this seems to be an issue again https://github.com/nwg-piotr/nwg-panel/issues/240#issue-1828936171
