### ISSUE TITLE
[BUG] Some icons in nwg-panel-config don't load properly if your icon theme is not Papirus

### ISSUE THREAD

**Issue by tewkanz** [nwg-piotr/nwg-panel#139]
**Describe the bug**
Some of the icons used in nwg-panel-config are referenced by names that aren't present in Adwaita (default for Gnome) or Breeze (default for KDE). It'd be nice if using Papirus wasn't a hard requirement. 

**To Reproduce**
1. Set your icon theme to something other than Papirus
2. Open nwg-panel-config.

**Expected behavior**
All of these icons have functional equivalents in Adwaita, they just aren't called 'gtk-edit', or 'gtk-go-up', or 'gtk-go-down'.

**Screenshots**
![image](https://user-images.githubusercontent.com/5669979/184552403-ea9e0258-656d-4e66-84b3-fcae6a2fa2f4.png)

**Desktop (please complete the following information):**
 - nixOS 22.05
 - Sway 1.7 
 - Panel version 0.73

**Additional context**
In Adwaita:
gtk-go-up => go-up
gtk-go-down => go-down
gtk-edit => document-edit
gtk-remove => list-remove
gtk-add => list-add
gtk-apply => object-select

Admittedly, these aren't as expressive as the names in Papirus :(

**Comment by nwg-piotr** [comment]
You're right. I always have something more urgent to do, but this needs to be fixed.

**Comment by nwg-piotr** [comment]
Should be fixed now.
