### ISSUE TITLE
[FEATURE REQUEST] Fixed length scrolling text box

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-panel#146]
**Is your feature request related to a problem? Please describe.**
Not particularly, but the only thing I haven't been able to replicate since migrating from waybar that I actually miss was a scrolling cryptocurrency price monitor. I've been able to get this script to display information on the panel, but not in a reasonable area. It takes quite a bit of bar space to show the json data, so I'd likely also have to write some kind of translational script to make it look nice, but I am not sure how I'd get a scrolling text box in the panel. 

**Describe the solution you'd like**
The option to create a fixed length box to display script information or monitor something, that includes the option to make overflowing text scroll instead of bleed into the next space.

**Describe alternatives you've considered**
Waybar has this so I assume theres a way to add a bar to the panel with waybar, but that seems like a somewhat bloated method for just a cryptocurrency monitor. But then again so is adding a feature. I just thought it would be cool. 

EDIT: Adding the ability to execute scripts in the tool tip would be an interesting alternative

**Comment by nwg-piotr** [comment]
Could you show me the script that produces the output?

**Comment by nwg-piotr** [comment]
After some testing: I find it doable only if you, depending on the length of the content you'd like to read, can accept scrolling by 1 character once a second. I gave it a try on the Playerctl module, and it seems that scrolling in smaller intervals results in unreasonable CPU usage.

I'll do some further testing, and publish the panel with the Playerctl module capable of scrolling the track metadata, if it turns out to make sense. Then we can discuss your feature request.

**Comment by xi-pinmping** [comment]
My bad, it has been very busy for me lately and I did not see this until now. I do not have a functional script yet but Im working on it and close but fighting with little things. My time has sadly been monopolized elsewhere lately and I'm still a bit novice with coding in some areas. 

Although I don't have the script yet I can paint a picture. I just want like a crypto price ticker around where playerctl is. Since playerctl isn't always in use I thought it would be cool to have in its place a short ticker for one or two cryptos using the coinmarketcap api to check for price change in a day.

**Comment by nwg-piotr** [comment]
OK, but I need answers to a few questions I asked above.
