### ISSUE TITLE
[FEATURE REQUEST] brightness panel preference vs control settings

### ISSUE THREAD

**Issue by envolution** [nwg-piotr/nwg-panel#150]
It is quite confusing (to me) for the brightness control preference to allow differential management tools between:
[ panel preferences window ] <-> [ control settings window ].

I suggest either pinning them together, or add to the information widget to inform the end-user to verify both locations are configured to their intended tool.  In my case it took me hunting through the source code to find that it is to be configured in two different locations.

(experienced while enabling ddcutil - very nice functionality by the way!)

**Comment by nwg-piotr** [comment]
ddcutil support is a bonus, and not really useful, as communication takes ages. I wondered whether to add it at all. The module author started working on better integration, but then disappeared, and I haven't heard from him in months. I'm not a fan of the Brightnes slider module at all, and, if I it's *really* necessary, I use [ddcpopup](https://github.com/nwg-piotr/ddcpopup) I wrote in go. Though it's far from perfection, too.
