### ISSUE TITLE
Trying to install on FreeBSD [BUG]

### ISSUE THREAD

**Issue by phijazz** [nwg-piotr/nwg-panel#162]
I'm trying the panel on freebsd, however I have that problem
❯ uname -r
13.1-RELEASE-p4
❯ sway -v
sway version 1.7
❯ nwg-panel -v
nwg-panel version 0.7.12
❯ nwg-panel
Traceback (most recent call last):
  File "/usr/local/bin/nwg-panel", line 33, in <module>
    sys.exit(load_entry_point('nwg-panel==0.7.13', 'gui_scripts', 'nwg-panel')())
  File "/usr/local/lib/python3.9/site-packages/nwg_panel/main.py", line 348, in main
    signal.signal(sig, signal_handler)
  File "/usr/local/lib/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal number out of range

❯ env | grep SWAYSOCK
SWAYSOCK=/var/run/user/phil/sway-ipc.1001.77233.sock

**Comment by nwg-piotr** [comment]
Well, I know nothing on BSD. Does the [signals list](https://man7.org/linux/man-pages/man7/signal.7.html) vary from what we have on Linux?

**Comment by phijazz** [comment]
Here is the list, under tcsh
> kill -l
HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS 
PIPE ALRM TERM URG STOP TSTP CONT CHLD TTIN TTOU IO XCPU 
XFSZ VTALRM PROF WINCH INFO USR1 USR2 LWP

**Comment by nwg-piotr** [comment]
On the `fix162` branch I've added a try/except block to the loop which we subscribe to signals in. I hope it to start on FreeBSD. Regardless of if it starts or not, in the `stderr` output we should see the signal that crashes the program on the `master` branch. 

Could you try:

1. Clone & run the panel from the `fix162` branch;
2. check if it works for you;
3. show me the output?
