### ISSUE TITLE
Force refresh of executor

### ISSUE THREAD

**Issue by varac** [nwg-piotr/nwg-panel#164]
**Is your feature request related to a problem? Please describe.**

I wrote an quick and dirty alertmanager executor, which works fine. However, if I want to refresh it's status, I don't know any other way than waiting for the end of the current interval.

**Describe the solution you'd like**

I'd like to have an option to force a refresh (a.k.a. force-end the current interval), configurable i.e. via right-click.

**Comment by nwg-piotr** [comment]
Well, it could be done via a signal, e.g. SIGUSR1. However, we have just a couple of signals possible to use, and virtually endless number of executors & other modules. I need to think about it.

**Comment by nwg-piotr** [comment]
@varac I've added experimental support for signals in range `SIGRTMIN+1` to `SIGRTMAX`. Would you be able to test the `signals` branch?

![image](https://user-images.githubusercontent.com/20579136/206343163-1021868c-7979-453f-be57-90a9943e3f78.png)

**Comment by nwg-piotr** [comment]
Very well. I added a sample executor. Check discussions for details. Submit you own executor if you have one.

**Comment by varac** [comment]
@nwg-piotr Nice, it works like it should, thanks !!

**Comment by nwg-piotr** [comment]
Very well. For now I've only found one possible appliance on my machine: keyboard layout switcher. I'd be grateful if you could share other ideas.

**Comment by nwg-piotr** [comment]
Thanks!
