### ISSUE TITLE
[Feature Request] Hide workspace labels from sway-taskerbar

### ISSUE THREAD

**Issue by anonymous-user** [nwg-piotr/nwg-panel#170]
I have setup nwg-panel with the sway-workspaces and sway-taskbar modules however it seems the latter also shows workspace numbers. This seems redundant and I would like a way to hide this workspace labels from the taskbar.

![test](https://user-images.githubusercontent.com/4295854/206954200-c73a258b-e39d-4ffb-be82-9f0a688c82dd.png)

If hiding these labels is already possible, please share how.

**Comment by nwg-piotr** [comment]
Using the SwayWorkspaces together with the SwayTaskbar module is redundant, as you have all you need in the SwayTaskbar module. Workspace numbers will be always visible. You can only turn off showing them as buttons.

![image](https://user-images.githubusercontent.com/20579136/207168957-98f4210b-8ee9-4fbd-a3b0-c5c647979eb6.png)

**Comment by anonymous-user** [comment]
I kinda like having the workspaces numbers on the very left separate from the taskbar though. Oh well.
