### ISSUE TITLE
nwg-panel hangs when resuming from standby/hibernation (0.7.15)

### ISSUE THREAD

**Issue by envolution** [nwg-piotr/nwg-panel#173]
````/usr/bin/python /usr/bin/nwg-panel -c preset-0 -s preset-0.css
Dependencies check: {'light': True, 'brightnessctl': True, 'ddcutil': False, 'pamixer': True, 'pactl': True, 'playerctl': True, 'netifaces': True, 'btmgmt': True, 'wlr-randr': False, 'upower': True, 'swaync': True, 'python-requests': True}
Running on sway
Error loading json: [Errno 2] No such file or directory: '/home/user/.local/share/nwg-panel/calendar.json'
executor name: executor-updates
Panel 'top': output: eDP-1, position: top, layer: bottom, width: 1920, height: 30
executor name: executor-cpuav
executor name: executor-cpubar
executor name: executor-temp
executor name: executor-memory
executor name: executor-drives
Panel 'bottom': output: eDP-1, position: bottom, layer: bottom, width: 1920, height: 30

(nwg-panel:34704): Gdk-CRITICAL **: 04:04:29.540: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(nwg-panel:34704): Gdk-CRITICAL **: 04:04:29.541: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(nwg-panel:34704): Gdk-CRITICAL **: 04:04:29.541: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

(nwg-panel:34704): Gdk-CRITICAL **: 04:04:29.541: gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed

...
``
shift+mod+c reloads as expected, but is required after every resume

**Comment by nwg-piotr** [comment]
It'll be difficult to me to check what's happening, as my hybrid graphics never gets back to life after putting the laptop to sleep. It looks like your display is not yet ready. Are you on single- or multi-headed setup? Is your panel attached to a certain output? 

We only use `get_scale_factor` in the Tray module. Does your error occur if you turn the Tray module off?

**Comment by envolution** [comment]
Yes it still happens without the tray module.

The tray module seems to not be using get_scale_factor either (commented out), and I couldn't find it anywhere in the panel source either.

If I quickly resume the system- the panel disappears, and the error I reported doesn't show up, so it may not be especially helpful in troubleshooting

**Comment by nwg-piotr** [comment]
We need to clarify what *nwg-panel hangs* means. Do you mean that it's visible, but frozen, or maybe you see no panel at all?

**Comment by envolution** [comment]
Sure, sorry for not clarifying;

The only display is the built-in laptop display, and the GPU is an integrated Intel UHD 620

While trying to get debugging messages for this report:
- I killed the panel process and ran it through a terminal
- I then put the device in standby by closing the lid
- Then opened the lid to resume

Observation: The panel was not visible by the time the display turned on, and the panel script process continued running - the only debug message during this time is the one I reported initially.  

If i perform these same steps more quickly, the debug message does not appear, and the symptom of the invisible panel is the same.
