### ISSUE TITLE
Codebase refactor/rewrite

### ISSUE THREAD

**Issue by TheRealLorenz** [nwg-piotr/nwg-panel#174]
**Is your feature request related to a problem? Please describe.**
Recently I wanted to develop a module for idle-inhibition, but right when I opened the repo in my editor my lsp and linters started to complain like crazy for formatting guidelines, code guidelines, type checks, unresolved imports and other errors.

**Describe the solution you'd like**
I think it would be nice to have the code refactored to follow pep8 style guides and resolve all gtk import alerts.

**Additional context**
I don't want to blame anyone who contributed to this codebase or the author himself. I love the nwg-shell project and it improved my sway experience A LOT.

I'd do the job myself, with some patience, because I think it would be worth it. Now I'm just looking for approval and/or a useful discussion about the topic. I would also be open to a complete rewrite in another programming language, but I definitely know this may not be the right answer.

Waiting for feedbacks!

**Comment by TheRealLorenz** [comment]
Not entirely sure PEP8 is followed, but nvm. I'll try to develop the idle-inhibit module anyway

**Comment by nwg-piotr** [comment]
Yes, please. Whatever you change in coding style, will disappear as soon as I save the code on my side, so it's pointless.
