### ISSUE TITLE
continuous output from executors

### ISSUE THREAD

**Issue by mildred** [nwg-piotr/nwg-panel#176]
**Is your feature request related to a problem? Please describe.**

I need to monitor the CPU load of my system, but at times of high load, spawning a new process can takes time and because of this, the executor might not execute unless the process is already running

**Describe the solution you'd like**

Executors should have an option to push updates to the panel on their own

**Comment by nwg-piotr** [comment]
> Executors should have an option to push updates to the panel on their own

I'm afraid it's impossible. They are being executed by the panel.

**Comment by nwg-piotr** [comment]
Same here, plus the possibility to trigger refresh on a signal: `SIGRTMIN > number <= SIGRTMAX`.
