### ISSUE TITLE
Missing features in workspaces

### ISSUE THREAD

**Issue by mildred** [nwg-piotr/nwg-panel#178]
**Is your feature request related to a problem? Please describe.**

Trying to migrate from swaybar to nwg-panel and I am missing a few things

**Describe the solution you'd like**

- mouse scroll on workspace list should move to previous/next workspace
- when the panel is shown on all outputs, the workspace list should not contain the workspaces that do not belong to the current output

**Comment by nwg-piotr** [comment]
Those features are not "missing", but not planned. I'll take a look at it when I have no urgent work to do.

**Comment by mildred** [comment]
You're right but most other panels have this. I implemented it in the PR above. It jut does not work with the trackpad, I don't know why.
