### ISSUE TITLE
[BUG] tray module do not display IconPixmap

### ISSUE THREAD

**Issue by mildred** [nwg-piotr/nwg-panel#192]
**Describe the bug**

The try shows a cross in a red circle icon instead of the application icon. This seems to happen for flatpak applications since ulauncher has its own icon.

**To Reproduce**

- install Telegram flatpak client
- run Telegram flatpak
- it does not show its icon in the tray but an invalid icon instead

**Expected behavior**
Telegram icon should show up

**Desktop (please complete the following information):**
 - Linux distribution : Fedora 37
 - Sway version: sway version 1.7
 - Panel version my own pull request on top of d223423e044359ed5c04843030c7025f597604d6

**Comment by mildred** [comment]
it has an IconName defined but set to the empty string, that's why

**Comment by nwg-piotr** [comment]
I installed Telegram with flatpack and the icon in on its place. Are you sure the problem is on on panels side?

**Comment by mildred** [comment]
It seems that there is an incompatibility with the panel code and how Telegram uses the icon for the tray. Telegram does not specify an icon name, but instead of not specifying it (property absent) the property is defined to be the empty string. The fix is to check that the icon name is not the empty string to use the icon, else use pixmap if available.

**Comment by nwg-piotr** [comment]
Could you make a separate PR out of it? What's currently on the branch, crashes my machine, and is complicated enough to discourage me from searching the reason.

**Comment by vivia1990** [comment]
Hi, any update about this?

**Comment by mildred** [comment]
Sorry for the delay, I rebased the PR
