### ISSUE TITLE
Install error search for a module name Pyrex

### ISSUE THREAD

**Issue by bluebyt65** [nwg-piotr/nwg-panel#2]
I tried to install on Archlinux with wayfire, I get this error.
ModuleNotFoundError: No module named 'Pyrex'

**Comment by nwg-piotr** [comment]
Have you installed `python-setuptools`?

**Comment by bluebyt65** [comment]
Yes I have python-setuptools 1:53.0.0-1

**Comment by nwg-piotr** [comment]
Well, the error seems to come from the `pyalsa` module. It should depend on cython, not pyrex. Try installing the `python-pyalsa` package. I'll remove this dependency from `setup.py`.

**Comment by bluebyt65** [comment]
Yes it's working after I have installed python-pyalsa.
The fun can start now thanks :)

**Comment by nwg-piotr** [comment]
Thanks for pastebin. It was helpful. By the way I discovered one more bug. Will push fix in a minute.
