### ISSUE TITLE
[BUG] Executors occaisonally loading indefinitely 

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-panel#211]
**Describe the bug**
Currently experiencing some weird behavior. At boot normally executors function fine but eventually they are locking up to the point I can no longer use any of them, see anything but the little loading circle arrow, or even see the outline of the box on hover.

**To Reproduce**
Refresh current session or sit with it open long enough

**Expected behavior**
Executors continually update without blanking out indefinitely 

**Screenshots**
![nwg-panel-error](https://user-images.githubusercontent.com/84921777/235373558-4d50dcd2-703e-475a-b483-2f98c68a1522.png)

**Desktop (please complete the following information):**
Arch (labs) Linux 6.2.13-arch1-1
sway version 1.8.1
nwg-panel version 0.8.5

**Additional context**
Typically it returns after a few minutes but does not update everything else on time. This is on multiple monitors and single, when on multiple monitors each screen will be stuck displaying different values.

**Comment by nwg-piotr** [comment]
It doesn't occur on any of my machines. No idea at the moment.

**Comment by xi-pinmping** [comment]
After the last update issue still persists, I have tried finding more info on the issue through starting the panel in cli, but the output appears to yield no errors
`

Running instance found, PID 3718, sending SIGINT
PID 3718 still alive, sending SIGKILL
Running no name instance killed, PID 3718
Common settings {'restart-on-display': True, 'restart-delay': 500}
Dependencies check: {'light': True, 'brightnessctl': False, 'ddcutil': True, 'pamixer': True, 'pactl': True, 'playerctl': True, 'netifaces': True, 'btmgmt': True, 'wlr-randr': True, 'hyprctl': False, 'upower': True, 'swaync': True, 'python-requests': True}
Running on sway
Panel 'top': output: eDP-1, position: top, layer: bottom, width: 1920, height: 30
Panel 'top': output: DP-4, position: top, layer: bottom, width: 1360, height: 30
Panel 'top': output: DP-5, position: top, layer: bottom, width: 1920, height: 30
Weather file: /tmp/nwg-openweather-weather-1660270864.434005
Forecast file: /tmp/nwg-openweather-forecast-1660270864.434005
Alerts file: /tmp/nwg-weatherbit-alerts-1660270864.434005
12:33:15 Loading weather data from file
12:33:15 Loading forecast data from file
Panel 'bottom': output: eDP-1, position: bottom, layer: bottom, width: 1920, height: 30
12:33:15 Loading alerts data from file
Weather file: /tmp/nwg-openweather-weather-1660270864.434005
Forecast file: /tmp/nwg-openweather-forecast-1660270864.434005
Alerts file: /tmp/nwg-weatherbit-alerts-1660270864.434005
12:33:15 Loading weather data from file
12:33:15 Loading forecast data from file
Panel 'bottom': output: DP-4, position: bottom, layer: bottom, width: 1360, height: 30
12:33:15 Loading alerts data from file
Weather file: /tmp/nwg-openweather-weather-1660270864.434005
Forecast file: /tmp/nwg-openweather-forecast-1660270864.434005
Alerts file: /tmp/nwg-weatherbit-alerts-1660270864.434005
12:33:15 Loading weather data from file
Panel 'bottom': output: DP-5, position: bottom, layer: bottom, width: 1920, height: 30
12:33:15 Loading forecast data from file
12:33:15 Loading alerts data from file
`

**Comment by nwg-piotr** [comment]
Can't do anything until I know how to reproduce the issue. It still hasn't occurred on any of my machines. @MoetaYuko what do you think?

**Comment by MoetaYuko** [comment]
I occasionally got the issue, especially after reboot, but I have no idea what's the root cause because it's hard to reproduce, and don't print any useful logs when it occurs.

**Comment by xi-pinmping** [comment]
I may have found the initiating issue. When I reboot its normally fine for a minute but the second I open spotify or an application seems to be when it lags, normally when opening it on monitors that aren't my laptop's or the screen I start on. I connect to my other monitors through a dock and spotify is automatically sent to workspace 9 which is my monitor. When I am not attached to the dock there is no issue. This may be unrelated but recently I also lost the ability to set volume on any external displays through anything but pavucontrol. No command seemed to change it, pipewire or pulse based.

**Comment by xi-pinmping** [comment]
Not sure what was relevant to fix this issue but after a week I think I can safely say I’m back to normal after a few updates and a change in location (and monitors by result) so I’m going to mark closed. Hopefully it doesn’t come up again lol.
