### ISSUE TITLE
[BUG] Python update breaks nwg-panel

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-panel#218]
**Describe the bug**
Recent arch linux python package update wave broke nwg, running it from command line asks me to install requests and after that it asks me to install python-i3ipc which is already installed through the arch repos. Installing though pip fixes the issue. 

**To Reproduce**
Update arch system with nwg-panel
Start nwg-panel

**Expected behavior**
Panel should start at boot or upon execution but does not due to dependency issue 

**Desktop (please complete the following information):**
Arch Linux 6.2.13-arch1-1
sway version 1.8.1
nwg-panel 0.8.7-1

**Additional context**
This seems to have broken a few python apps for me so if theres something I missed with the recent update please let me know lol

**Comment by nwg-piotr** [comment]
What makes you think it's a bug in the panel? It happens to every python app after the python upgrade. Just reinstall.
