### ISSUE TITLE
Sway taskbar loses data

### ISSUE THREAD

**Issue by gf3** [nwg-piotr/nwg-panel#22]
Not sure what happened here, but after several hours of use the taskbar seems to have lost its contents:

![2021-02-23T18:01:00,060682955-05:00](https://user-images.githubusercontent.com/18397/108919714-7f6fa480-7601-11eb-9653-612e2e8e2929.png)

Restarting the nwg-panel fixed the issue

**Comment by nwg-piotr** [comment]
The SwayTaskbar module doesn't store any own data. It takes them directly from the tree, every time it changes.

**Comment by gf3** [comment]
@nwg-piotr noted! it must have been unable to parse the tree or the tree was unavailable, and it could not correct itself from this state

**Comment by nwg-piotr** [comment]
Or eventually the i3ipc library failed in some way. One way or another the culprit seems to be outside the panel code.

**Comment by nwg-piotr** [comment]
Closing as not the panel code related.
