### ISSUE TITLE
[BUG] Panel Settings: "Custom Items" and "User Menu" are not accessible

### ISSUE THREAD

**Issue by Kvn0l** [nwg-piotr/nwg-panel#226]
**Describe the bug**
In the config app, Control sub-sessions "Custom Items" and "User Menu" are not accessible and output errors in terminal

**To Reproduce**
1. Open NWG Panel Settings app
2. Select a Panel to edit
3. Go to Control, select sub menus "Custom Items" and "User Menu", they aren't opening.
4. It don't crash either.
5. But errors appear when I run the panel from terminal.

**Expected behavior**
Expected to work normally.

**Desktop (please complete the following information):**
EndeavourOS
Hyprland v0.25.0-45-gad244190
nwg-panel version 0.9.2

**Additional context**
Here's the output

When I click Custom Items:
`Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nwg_panel/config.py", line 3756, in edit_custom_items
    custom_items_grid = ControlsCustomItems(self.panel, self.config, self.file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_panel/config.py", line 3787, in __init__
    self.set_label_align(0.5)
TypeError: Gtk.Frame.set_label_align() takes exactly 3 arguments (2 given)`

When I click User Menu:
`Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/nwg_panel/config.py", line 3765, in edit_user_menu
    custom_items_grid = ControlsUserMenu(self.panel, self.config, self.file)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/nwg_panel/config.py", line 3946, in __init__
    self.set_label_align(0.5)
TypeError: Gtk.Frame.set_label_align() takes exactly 3 arguments (2 given)`

Additionally this appears a lot, but I don't think it's relevant to the issue:
`(nwg-panel:81614): Gdk-CRITICAL **: 18:19:45.364: gdk_wayland_window_set_dbus_properties_libgtk_only: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed`

Anyway, I'm gonna test in sway too, maybe it's hyprland-only problem

**Comment by Kvn0l** [comment]
Tested on Sway (version 1.8.1), exact same problem.

**Comment by nwg-piotr** [comment]
This must be a change to GTK3, as it has always worked without the 3rd argument. Even the latest stubs know nothing about it, and mark the last argument "unexpected". I'll fix it in a minute.

**Comment by Kvn0l** [comment]
Nice! Updated to latest commit, confirmed working. Thank you!

**Comment by nwg-piotr** [comment]
AUR package on the way.
