### ISSUE TITLE
[WIKI UPDATE] Installation page update for version 0.9.7

### ISSUE THREAD

**Issue by t0fik** [nwg-piotr/nwg-panel#230]
Updated Installation wiki page to reflect changes in dependencies in version 0.9.7.
Updated wiki repository clone url: https://github.com/t0fik/nwg-panel.wiki.git
Github do not support PRs for wiki repository.

**Comment by nwg-piotr** [comment]
I've just made this Wiki public. Or at least I hope so.

**Comment by t0fik** [comment]
Changes are not visible. I found that workaround to merge changes to Wiki from forked repository: https://gist.github.com/larrybotha/10650410

**Comment by t0fik** [comment]
I've updated upstream Wiki page
