### ISSUE TITLE
Missing configs & no info on making them/ possible miss depends

### ISSUE THREAD

**Issue by webbb82** [nwg-piotr/nwg-panel#232]
alright first let me say I love this project and really want to use it, I downloaded and installed everything but the shell because im on nixos and that was the only one missing. 
     I have the editing the panel with the edit program but nothing is being added or changed. Ive added  of each of everything from, tray, menu, buttons and nothing shows Ive tried to apply then apply restart nothing, I cant find any documentation really on github I could be blind and cant find it.

Also im missing configs for the panels, menu,dock bar and so on. Again no documents to help make configs, again maybe im blind

I got the menu up and i  can only add aps to favorite and otherwise its empty. The only files i have a a few css files. p[lease tell me im missing someehting because I cant belive this projet is in this shape. I know its not because I didnt see a ton of bug reports on these issues. so something is missing, I dont think the shell would that this?

**To Reproduce**

**Expected behavior**
To be able to use the modules after some learning curve

**Screenshots**

**Desktop (please complete the following information):**
 - NIXOS
 - HYPRLAND
 - nwg-panel version 0.7.17

**Additional context**

**Comment by nwg-piotr** [comment]
All the shell components, when used standalone, should create one basic config file on 1st run. If you'd like to get all the configs provided with nwg-shell installation, feel free to copy them from here: https://github.com/nwg-piotr/nwg-shell/tree/main/nwg_shell/skel, to their appropriate paths.
