### ISSUE TITLE
[Feature Request] Send signal to hide Panels completely (including reserved space)

### ISSUE THREAD

**Issue by ZetaArashi** [nwg-piotr/nwg-panel#234]
**Is your feature request related to a problem? Please describe.**
I recently moved to nwg-shell from a less comprehensively integrated suite of tools, one of which was waybar. I'm extremely happy with it so far, but I haven't found a way to set up a keybind to hide the panels entirely. My daily workflow usually involves hiding panels entirely while I'm coding during the day as a focus mechanism; is there a way to perform this already?

I've already attempted a -SIGUSR1, which doesn't seem to work. I did note the functionality for dwl that's built in, but that doesn't seem to help in this case.

**Describe the solution you'd like**
Ideally either a keybind to hide the panels entirely could be added to the settings panel, or a note in the documentation for a signal that can be passed to it via a keybind.

**Describe alternatives you've considered**
Currently I'm considering killing the panels entirely and restarting them when I need them via shell scripting. As the styling is handled via CSS, I may also try setting the height to 0 and reloading the configuration that way to see if it works. 

**Additional context**
Not much more to say. "No" is a perfectly reasonable response, as would be "It already does that and you're blind" -- I just figured I'd ask. Thank you for your work on this project, it's lovely!

**Comment by nwg-piotr** [comment]
Hi,

Why not?

As people, including myself, use multiple outputs, this should be selective. I'll try to use a signal in range `SIGRTMIN > hide_show_sig_num <= SIGRTMAX` for each panel.

**Comment by nwg-piotr** [comment]
I'll make a new release when it's tested well enough.

**Comment by ZetaArashi** [comment]
You are my hero! Thank you!
