### ISSUE TITLE
[BUG] Post two recent updates (...9.8/9.9) issues with panel displaying correctly

### ISSUE THREAD

**Issue by Brittle73** [nwg-piotr/nwg-panel#237]
**Describe the bug**
Since I updated to 9.8 for the first time in a week or so yesterday via yay (and then 9.9 today) I'm having some issues not just with icons on the panel, but even with some of the controls modules. Those were working fine, but I did notice last week or the week before that whenever I launched the GUI editor, made changes, and hit "Apply/Restart" it appeared to restart the panel, but would come back up with no changes. If you went back to the GUI you'd see that the changes were never committed. As of the system updates that I ran yesterday for the volume and bluetooth controls inside that panel my icons are broken and no information displays. It just shows a circular arrow and if I manually toggle that from inside the controls drop down and it launches blueman it appears to remedy itself, but the volume does not and it doesn't look like the correct output is present in the output switcher. I tried to disable even showing the output switcher and re-enabling via the GUI and it doesn't appear to do anything.

**To Reproduce**
The *ONLY* way I can get it to work mostly correctly is by manually running nwg-panel from the terminal. Restarting Sway with Super+Shift+C does restart it, but it comes back broken again, even if it was running by manual command prior. My Sway config includes "exec_always nwg-panel" and I tried commenting that out and just using "exec nwg-panel" and get the same results. Many, many reboots, restarts of Sway, making sure everything is up to date (pacman and yay), reinstalling nwg-panel and nwg-panel-git, manually uninstalling all panel packages and downloading and installing 9.7, so on and so forth.

**Expected behavior**
nwg-panel launches just fine and shows the correct/mostly accurate (probably polling delay) data, and changes made in the recommended GUI should remain intact when hitting Apply/Refresh and rebooting/reloading Sway, etc.

**Screenshots**
What a chunk of the bar looks like when misbehaving:
![image](https://github.com/nwg-piotr/nwg-panel/assets/84404407/934f24be-a86a-49db-b416-88229297f7b6)

Same spot when ran manually from terminal (looks good):
![image](https://github.com/nwg-piotr/nwg-panel/assets/84404407/864ce768-12a3-447c-9c4b-d578386b9615)

**Desktop (please complete the following information):**
 - Arch (up-to-date)
 - Sway version `sway -v': 1.8.1
 - Panel version `nwg-panel -v`: 0.9.9

**Additional context**
Everything should be up to date. Not sure why it started acting up. I have read where Python updates can sometime break stuff like this, so I reinstalled nwg-panel several times per some of the notes I saw, unless reinstalling Python itself was the recommendation, not just nwg-panel. Additional context:
Surface Pro 6
Arch/Sway
Most of the nwg- apps are installed
i5 / 8GB RAM / plenty of SSD capacity

THANK YOU!

PS - if I forgot/left out/didn't know how to provide some tidbit of information, please just let know and I'll do my best to fix it :)

**Comment by MoetaYuko** [comment]
I noticed this issue recently as well, and the cause is that `btmgmt info` hangs infinitely when starting via exec_always:
https://github.com/nwg-piotr/nwg-panel/blob/42f8b23140009c891d29359e48c2401064ad5a05/nwg_panel/tools.py#L712

I don't use the `bluetooth` module so I proposed https://github.com/nwg-piotr/nwg-panel/pull/238 to skip it. Still need a proper fix.
