### ISSUE TITLE
[BUG] nwg-panel does not scale correctly leaving it only partly visible

### ISSUE THREAD

**Issue by Sivecano** [nwg-piotr/nwg-panel#240]
**Describe the bug**
when changing the per-display scaling on either sway or hyprland using nwg-shell the panel does not scale correctly leaving important components of it offscreen. the panel does not respect scaling horizontally.
this issue persists using the binary aur packge on up-to-date archlinux as of the 31st of juli 2023

**To Reproduce**
1.  open nwg-panel on hyprland or sway on a display with greater than 1.0 scaling
2. see, that large parts of the top and bottom panel are off-screen
3. see, that the width has been set to auto 

**Expected behavior**
I expect the panel to scale with the compositor and for all of it to be visible

**Desktop (please complete the following information):**
 - Linux distribution: Arch (most recent update c.a. 31st of July 2023
 - Sway version `sway -v`: sway version 1.8.1
 - Panel version `nwg-panel -v` nwg-panel version 0.9.10

**Additional context**
using Hyprland version 0.27.2-1 from arch repos

**Comment by Sivecano** [comment]
correction: some rescaling takes place after restarting the panel manually

**Comment by nwg-piotr** [comment]
The panel checks the screen dimensions on startup. You need to restart if you change scaling.

**Comment by Sivecano** [comment]
after testing it, this seems to work on sway but not hyprland.

**Comment by Sivecano** [comment]
thanks, don't be too stressed about it.

**Comment by nwg-piotr** [comment]
I'm about to release a new version one way or another. The more fixes, the better.

**Comment by Sivecano** [comment]
A thing I noticed while experimenting like this, is that the bar will still be too big if the screen can't fit all the widgets in it. but I'm not sure how this should be approached and the current solution is fine. though, the drop down menu on the top right being inaccessible does pose somewhat of a problem.

**Comment by nwg-piotr** [comment]
> the bar will still be too big if the screen can't fit all the widgets in it

This is impossible to avoid. Also you shouldn't use wide Left/Right modules having something (e.g. clock) in the center modules. This forces columns to be homogeneous, as the only way to keep center modules centered.
