### ISSUE TITLE
Transparent background via css

### ISSUE THREAD

**Issue by methuselah-0** [nwg-piotr/nwg-panel#241]
**Is your feature request related to a problem? Please describe.**
Setting background: transparent in css doesn't work as in waybar.

**Describe the solution you'd like**
make the background of the panel transparent as with waybar.

**Describe alternatives you've considered**
Ive tried * { background: transparent; }
 #panel-top { background: transparent; }
but it only gives me a light grey background at best, the sway nc side panel is transparent though.

**Comment by nwg-piotr** [comment]
Use the name you gave to the panel window. In the picture below: `panel-top`.

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/4f655929-bc44-4c9e-a304-386380da2179)

**Comment by methuselah-0** [comment]
I think maybe there was something wrong with the default css, because when I removed almost everything and added only transparency it worked.
