### ISSUE TITLE
Adding more styling classes - Hyprland

### ISSUE THREAD

**Issue by Visual-Dawg** [nwg-piotr/nwg-panel#243]
**Is your feature request related to a problem? Please describe.**
It is a bit hard to style the bar currently. There are no classes for `modules-right|left`, `hyprland-workspaces`, `hyprland-tasks`, `player-ctl` and maybe more.

**Describe the solution you'd like**
Adding unique classes to the modules and the layout.

**Describe alternatives you've considered**
Using selectors like `window > box > box > box > box`, which break when the layout gets modified.

**Comment by Visual-Dawg** [comment]
Just discovered the `css-name` attribute, but it does not seem to do anything for the names modules.

**Comment by nwg-piotr** [comment]
Your problem is worded too vaguely. You have to give concrete examples of what you would like to do but it is not possible.

**Comment by Visual-Dawg** [comment]
Hey, thank you for the answer and yes I will be more concrete.

I want to style my bar and give the different sections a floating pill look. A bit like this:
![image](https://github.com/nwg-piotr/nwg-panel/assets/28539403/4dd2adb4-ed4e-432b-8284-d18416c9a9c2)


However, there are no selectors for the different sections of the layout, like `#left` | `#middle` | `#right`. ( And maybe also `#left-inner` | `#middle-inner` | `#right-inner` to apply the background only to the occupied space and not the whole section )

Also the modules I mentioned (and maybe more) will not generate the `class-name` specified in `config`, thus they cannot be targeted by css-selectors specifically. 

I looked in the code and while I dont really know Python, the modules which can generate class name for themselves via the `css-name` property in the config do have `self.label.set_property("name", settings["css-name"])`, whereas for example the Hyprland modules do not.

**Comment by iggut** [comment]
+1 I was just trying to figure out how to do this. This feature would be greatly appreciated :D

**Comment by vivia1990** [comment]
Other styling missing feature?

I noticed that there's no way to use css special selector :hover, for example
```css
#clock:hover  { /* this is not triggering on widget hover */
}
```
So the only hover style i get is the (horrible) default with green borders. I digged into gtk 3 css and to enable float, a flag must be set on widget mouse hovering. Am I doing something wrong or is a missing feature?

**Comment by Visual-Dawg** [comment]
Any updates on this?

**Comment by nwg-piotr** [comment]
For fixed CSS IDs I added descriptions in corresponding config tabs (sway-taskbar, hyprland-taskbar, sway-workspaces, hyprland-workspaces).

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/8db51b18-7a9c-4365-9c65-c49d10052ae8)
