### ISSUE TITLE
Make shutdown command adjustable by settins gui

### ISSUE THREAD

**Issue by Schievel1** [nwg-piotr/nwg-panel#244]
This is about the menu that pops up when clicking the little downward facing arrow on the for right of the panel and then on exit

**Is your feature request related to a problem? Please describe.**
Systems that do not utilize systemd usually have a different command to shut down as non-root.

**Describe the solution you'd like**
The command should be changeable via the panel-settings gui

**Describe alternatives you've considered**
The commands can be changed in the config file
```
      "menu": {
        "name": "Exit",
        "icon": "system-shutdown-symbolic",
        "items": [
          {
            "name": "Lock",
            "cmd": "nwg-lock"
          },
          {
            "name": "Exit Hyprland session",
            "cmd": "hyprctl dispatch exit"
          },
          {
            "name": "Restart",
            "cmd": "loginctl reboot"
          },
          {
            "name": "Shutdown",
            "cmd": "loginctl poweroff"
          }
        ]
      },
```

**Comment by nwg-piotr** [comment]
You have a GUI for that:

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/806fc100-ef7d-4233-9e4e-1dc128e8d412)

**Comment by Schievel1** [comment]
oh yes, I missed that then
