### ISSUE TITLE
Power-menu applet without systemctl

### ISSUE THREAD

**Issue by Visone-Selektah** [nwg-piotr/nwg-panel#245]
HI! 
There's any way of use the power-menu in distros without systemd?

**Comment by nwg-piotr** [comment]
You mean this menu?

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/4db289bd-b229-4cc5-83eb-0f83885305df)

If so, this is fully user-configurable. You may enter any label with any command. Please find "Controls" in the panel settings.

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/6f585a41-968f-47d7-8252-dc8349d3b5bf)
