### ISSUE TITLE
[BUG] Panel can overflow when elements get too wide

### ISSUE THREAD

**Issue by SpeckledFleebeedoo** [nwg-piotr/nwg-panel#246]
**Describe the bug**
Elements on the panel may get pushed to the side and off the screen when there are too many things on the panel or individual elements become too wide. An easy way to make this happen is by using the hyprland taskbar while having items in all 3 positions.

**To Reproduce**
Add elements to each of the 3 positions (left, center, right) of the taskbar, then add a particularly wide element on the left or right. The hyprland taskbar is easy as it gets wider as more programs are open. For me a weather widget, a clock and the taskbar are enough to start pushing things off the side as soon as more than 3 windows are open.

**Expected behavior**
Not sure... Anything but items getting pushed off the screen.

**Screenshots**
![image](https://github.com/nwg-piotr/nwg-panel/assets/49042682/c6be9b10-ec3d-4888-9a44-d8ee4c681930)

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - ~~Sway~~ Hyprland version: 0.27.2-1
 - Panel version: 0.9.11

**Comment by SpeckledFleebeedoo** [comment]
![image](https://github.com/nwg-piotr/nwg-panel/assets/49042682/2870318f-2930-44ef-b1be-077336020c22)
Opening more windows has the interesting side effect of pushing items off the screen on both sides and creating more whitespace in the process

**Comment by nwg-piotr** [comment]
Duplicate of #95 and several other. Please read https://github.com/nwg-piotr/nwg-panel/issues/95#issuecomment-1053973777

**Comment by SpeckledFleebeedoo** [comment]
I see, thank you!
