### ISSUE TITLE
Outdated Nixpkg

### ISSUE THREAD

**Issue by etherrorcode404** [nwg-piotr/nwg-panel#247]
https://search.nixos.org/packages?channel=unstable&show=nwg-panel&from=0&size=50&sort=relevance&type=packages&query=nwg+panel

Nix Unstable still has the outdated package; 
nwg-panelVersion: 0.7.17

**Comment by nwg-piotr** [comment]
Report to the packager, please. I don't do packaging, except for AUR.

**Comment by etherrorcode404** [comment]
https://github.com/NixOS/nixpkgs/issues/249315
