### ISSUE TITLE
[BUG] system tray icons not visible 

### ISSUE THREAD

**Issue by blauch** [nwg-piotr/nwg-panel#248]
**Describe the bug**
I recently moved to nwg-shell from my "manual" sway setup. So far so good but the system tray is not working for me. When I open an app that goes to the tray then I see that the tray expands but no icon will appear. I enabled and disabled the system tray option for an app and could see the icon for network manager move left and right. I tried to click the area where the icon should be to no response.

**To Reproduce**
1. Launch an app that uses the system tray
2. The system tray will expand. no icon will appear

**Expected behavior**
When an app is in the system tray I expect to see the app's icon and get a menu on click

**Screenshots**
![swappy-20230817_170419](https://github.com/nwg-piotr/nwg-panel/assets/18649280/8cdd5c25-f63d-496e-8934-260c94b2ff5f)
![swappy-20230817_170659](https://github.com/nwg-piotr/nwg-panel/assets/18649280/0433f701-4dcf-4c39-8159-9e2bdd36c712)

**Desktop (please complete the following information):**
 - Linux distribution: Manjaro Linux 23.0.0
 - Sway version:  1.8.1
 - Panel version: 0.9.11

**Additional context**

**Comment by nwg-piotr** [comment]
As you see in your own picture, not all the the tray icons don't work. The problem refers to Electron apps and appeared after some Electron update in May this year. We have no solution so far.

Closing this issue as a duplicate. Please continue in #224.
