### ISSUE TITLE
Executor configured color

### ISSUE THREAD

**Issue by alexschneider** [nwg-piotr/nwg-panel#250]
**Is your feature request related to a problem? Please describe.**
I'm trying to migrate my i3blocks over to sway executors and while they're not completely compatible, the only thing I haven't been able to find a substitute for is [foreground/background colors](https://github.com/vivien/i3blocks#format), of which I make extensive use of in my blocks. I tried using [Pango markup](https://docs.gtk.org/Pango/pango_markup.html#pango-markup) to set color from my executors but that doesn't work either. 

**Describe the solution you'd like**
Ideally either foreground/background color would be supported as the output of an executor script similar to i3blocks or the executor could output Pango markup to format/style the output.

**Comment by nwg-piotr** [comment]
Please remember that this is GTK. Probably pango markup would work well, but we already have all the tools we need to change executors appearance. You may change the "Root CSS name" value for any certain executor in the panel config, and then define the same `#id` in the panels style sheet:

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/70eb221d-6d98-4809-877a-9dec324ecf86)

**Comment by nwg-piotr** [comment]
GTK styling is all done via css. The only thing I can do is to add pango support to the label.

**Comment by alexschneider** [comment]
Pango markup support to the label would be amazing in that case.

**Comment by nwg-piotr** [comment]
This is just a small change.

**Comment by nwg-piotr** [comment]
![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/4bc7791b-0ef8-4779-9269-bde4938d8865)

**Comment by nwg-piotr** [comment]
Added in aaaa2ff76a4274cd3d8f3578ff199fefa3f62dd1
