### ISSUE TITLE
[BUG] Volume control actually does not change the volume

### ISSUE THREAD

**Issue by Schievel1** [nwg-piotr/nwg-panel#258]
**Describe the bug**
When I raise or lower the volume in the panel the actual volume of the sound output does not change. 

**To Reproduce**
1. Lower or raise volume

**Expected behavior**
Volume changes

**Screenshots**

**Desktop (please complete the following information):**
Gentoo
hyprland 0.30.0
nwg-panel version 0.9.14

**Additional context**
I guess I am just missing a program to change the volume programmatically. But I don't know which. I don't use pulseaudio an my system, only pipewire. So which is nwg-panel using in this case?

**Comment by nwg-piotr** [comment]
You need either `pamixer` or `pactl` package:

```python
def set_volume(percent):
    if nwg_panel.common.commands["pamixer"]:
        subprocess.call("pamixer --set-volume {}".format(percent).split())
    elif nwg_panel.common.commands["pactl"]:
        subprocess.call("pactl set-sink-volume 0 {}%".format(percent).split())
    else:
        eprint("Couldn't set volume, no 'pamixer' or 'pactl' found")
```

**Comment by Schievel1** [comment]
I have pactl but when I run this command in the terminal the slider in nwg-panel changed but the volume doesn't.

I guess this has nothing todo with nwg-panel then

**Comment by nwg-piotr** [comment]
Yes, it must be a problem with your system.

**Comment by Schievel1** [comment]
It on the terminal works when I use the sink 1 like this:
`set-sink-volume 1 100%`

So apparently my system has a sink 0 that isn't used. 
Couldn't nwg-panel use the command `pactl set-sink-volume @DEFAULT_SINK@ {}` instead? I am by no means an expert on this, but at first glance this should cover more edge cases.
