### ISSUE TITLE
[BUG] Sway Taskbar icons missing for some programs

### ISSUE THREAD

**Issue by buckket** [nwg-piotr/nwg-panel#259]
**Describe the bug**
The Sway Taskbar module does not show the appropriate icon for some programs, just a generic placeholder.

**To Reproduce**
1. Enable Sway Taskbar module with "Show icon" turned on
2. Start Thunderbird or Signal-Desktop

**Expected behavior**
The program icon should be displayed in the taskbar instead of a placeholder, just like for any other program.

**Desktop:**
 - Arch Linux
 - sway version 1.8.1
 - nwg-panel version 0.9.14

**Additional context**
Here is the output of `swaymsg -t get_tree` for the two examples where the icon is not shown:
- con "Mozilla Thunderbird" (xdg_shell, pid: 2870, app_id: "thunderbird")
- con "Signal" (xwayland, pid: 61001, instance: "signal", class: "Signal", X11 window: 0x1600003)

The .desktop files for those programs on Arch are:
- org.mozilla.Thunderbird.desktop with `Icon=org.mozilla.Thunderbird`
- signal-desktop.desktop with `Icon=signal-desktop`

I don't know how nwg-panel actually implements the icon assignment, but both .desktop files also include a StartupWMClass field which matches the app_id or class of the program windows respectively, which could be used for this purpose.

**Comment by nwg-piotr** [comment]
I don't use thunderbird, but installed for testing, and your issue doesn't appear on my side:

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/1226b0be-46e5-4a70-9812-1b549fd70449)

Same if it comes to Telegram:

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/0ef8fd4d-3d21-4bba-b269-dc7d2d4625ca)

**Comment by buckket** [comment]
Okay, strange. 

When I search for Firefox it shows:
`/usr/share/icons/hicolor/scalable/apps/firefox.svg`

For Telegram (which also works for me):
`/usr/share/icons/hicolor/256x256/apps/telegram.png`

But when I search for Thunderbird no icon shows up, I have to explicitly search for `org.mozilla.Thunderbird` and then I get the correct icon, namely: `/usr/share/icons/hicolor/256x256/apps/org.mozilla.Thunderbird.png`

So it definitely exists and is installed but it doesn't seem to get associated with the Thunderbird process or window correctly.

**Comment by nwg-piotr** [comment]
I'm pretty sure it's an issue on you side. Try installing and setting some good icon theme, e.g. Papirus or Tela.

**Comment by buckket** [comment]
I’m not sure why I would need an additional icon theme.

The program icons are included with the program when you install the package via the package manager.

As I mentioned the Thunderbird icons are definitely installed and are at the right location. nwg-icon-picker even shows them when I enter the exact file name.

I just tried installing xfce4-appfinder and there the icons are all shown correctly, which leads me to believe that it has to be a problem with nwg-panel.

**Comment by nwg-piotr** [comment]
> I’m not sure why I would need an additional icon theme.

To find out if the icon theme the is the culprit. Of course you don't have to, but the panel has hundreds of users that have no such issue.

**Comment by buckket** [comment]
I just installed papirus-icon-theme, and now Thunderbird shows an Icon, but I’m pretty sure that's because papirus-icon-theme installs thunderbird.svg AND org.mozilla.Thunderbird.svg.

The correct naming scheme and icon as specified in the .desktop file is org.mozilla.Thunderbird though, so I’d expect nwg-panel to look an use that.

Signal still doesn’t work.

**Comment by buckket** [comment]
The problem seems to be the same as #64, but the proposed fix apparently doesn't work for me.

**Comment by nwg-piotr** [comment]
OK. I can search all `org.whatever.someone.invented`-named .desktop files every time the desktop file is not named as it should be (<app_id.desktop>), but it will cost quite a lot of additional disk operations. I'll push a fix, but I still strongly recommend using icon themes that provide well named icons. If we have just the `thunderbird` icon, we have no need to search .desktop files.

**Comment by erlehmann** [comment]
I think the fix in https://github.com/nwg-piotr/nwg-panel/commit/9bd89f1438fc80e9aff5422c8797f99355735858 could select the wrong icon for desktop files that use a language-specific icon, for example:
```
Icon[de] = foo
Icon[en] = bar
Icon = baz
```

**Comment by erlehmann** [comment]
> Why? The line will be split on "=" anyway. Actually I don't care much. We will never address all possible misbehavior. And parsing .desktop files is just a fallback.

Your code will not use the language-specific icon. It will, instead, use the first icon that was found.
