### ISSUE TITLE
[Feature request] Add  a way to adjust keyboard backlight

### ISSUE THREAD

**Issue by kuba3351** [nwg-piotr/nwg-panel#268]
Some laptops have a keyboard backlight. While using nwg-shell the keyboard backlight is turned off and there is no GUI for adjust it like there is for volume control or screen backlight.

Please add a module to control keyboard backlight. 

The backend command that can be used to control backlight is:
`light -Ss "sysfs/leds/tpacpi::kbd_backlight" <value between 0 and 100>`

**Comment by nwg-piotr** [comment]
This would be difficult for me to test. At the moment I have 2 backlit keyboards connected (internal + external) and no corresponding device in the `light -L output` :/.

```
❯ light -L
Listing device targets:
	sysfs/backlight/amdgpu_bl2
	sysfs/backlight/auto
	sysfs/leds/input24::compose
	sysfs/leds/input24::capslock
	sysfs/leds/input5::capslock
	sysfs/leds/input24::numlock
	sysfs/leds/input24::kana
	sysfs/leds/input24::scrolllock
	sysfs/leds/input5::scrolllock
	sysfs/leds/input5::numlock
	sysfs/leds/mmc0::
	util/test/dryrun
```
