### ISSUE TITLE
[BUG] Wrong battery icon while low battery and charging

### ISSUE THREAD

**Issue by kuba3351** [nwg-piotr/nwg-panel#270]
**Describe the bug**
When battery level goes bellow 20%, the battery icon changes to red to indicate that battery level is low, but when plug in to charger, the battery does not become green until it goes above 20%. I think battery charging indicator should have precedence over low battery indicator because when I plugged in charger while had low battery, I was confused that the battery does not charging. I had to wait some time to see that the percentage indicator is increasing.

**To Reproduce**
1. Wait until battery goes bellow 20%
2. Plug in charger
3. There is no any sign that the battery is charging, the icon is still red until level goes above 20%

**Expected behavior**
Battery icon should be green when plugged in to charger even if level is low

**Desktop (please complete the following information):**
 - Linux distribution: Fedora 39
 - Panel version `nwg-panel -v`: 0.9.16

**Comment by nwg-piotr** [comment]
You're right. Should be fixed now.
