### ISSUE TITLE
Vala Panel AppMenu Plugin

### ISSUE THREAD

**Issue by erfanmola** [nwg-piotr/nwg-panel#272]
Hi, it would be fantastic if you add support for Vala-Panel-AppMenu Plugin, the plugin is already ported into xfce4-panel, mate-panel, budgie, vala panel, ...

I don't know if here is right place to ask for this issue, but I suppose the nwg-panel dev can port the plugin to nwd-panel easier than the vala-panel-appmenu dev

Most of the part such as exporting the menus and etc is done by the plugin, the displaying part remains.

**Comment by nwg-piotr** [comment]
Not as long as I maintain the nwg-menu plugin.
