### ISSUE TITLE
[BUG] Window name length limit by actual display size

### ISSUE THREAD

**Issue by 1024th** [nwg-piotr/nwg-panel#273]
**Describe the bug**
I'm using the Hyprland Workspaces module. I use the setting 'Window name length limit' to prevent it becoming too long. Currently it calculates the window name length by the number of characters instead of the actual display size. This is not reasonable since the user may not use a monospace font. A large length limit causes overflow for wide characters (e.g., when the window name is 'wwww...'), and a small limit leads to the waste of space for thin characters (e.g. 'iiii...').

**Expected behavior**
Allow to set window name length limit by actual display size. (Something like the CSS width property?)

**Desktop (please complete the following information):**
 - Linux distribution: Arch Linux
 - Hyprland version `hyprctl version`
```
Hyprland, built from branch main at commit ad3f6886484e9adbab532de125e69a70c54fa13e dirty (opengl: check for introspection on special_blur).
Tag: v0.32.3-74-gad3f6886

flags: (if any)
debug
```
 - Panel version `nwg-panel -v`: 0.9.17

**Comment by nwg-piotr** [comment]
This would be very difficult to implement, and makes little sense.
