### ISSUE TITLE
[Feature request] per app volume control

### ISSUE THREAD

**Issue by Caliel666** [nwg-piotr/nwg-panel#274]
This is my number 1 feature request to have on any window manager, right now it's really hard to do it, having to rely on eww

the best alternatives are to use a separate app like pavucontrol or myxer, but i would rather have it integrated in the control center

something that looks like one of the features from this gnome extension would be amazing <https://github.com/qwreey/quick-settings-tweaks>

**Comment by nwg-piotr** [comment]
Sure it's doable. Would it be enough if it worked with the `pactl` backend only? I'm feeling too lazy to check if it's possible with `pamixer`. ;)

**Comment by nwg-piotr** [comment]
Teaser:

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/4b30fa1b-014c-4220-b273-bd37c33461fc)

**Comment by Caliel666** [comment]
Looks awesome! And sure, as long as it works with at least pulse audio and pipewire you can use whatever you want

**Comment by nwg-piotr** [comment]
Still some work left to do. Stay tuned.
