### ISSUE TITLE
[BUG] Nwg-Panel does not refresh Windows on wayland

### ISSUE THREAD

**Issue by kuba3351** [nwg-piotr/nwg-panel#277]
**Describe the bug**
I am using Nwg-shell and Wayland on Fedora for daily driver. I am facing an issue after running nwg-panel for some time.

When I open new Windows, closing, or moving between workspaces changes are not visible on nwg-panel, new Windows does not appear and closed windows still appears.

Restarting nwg-panel helps for some time and after a while it happens again.

Nwg-panel does not hang, other controls works as expected, only Hyprland taskbar module does not work correctly.

**To Reproduce**
1. Have nwg-panel running for a while
2. Open up new windows or close already opened or move to another workspace
3. Change is not visible on nwg-panel

**Expected behavior**
Change should be visible on nwg-panel

**Desktop (please complete the following information):**
 - Linux distribution: Fedora 39
 - Hyprland version: 0.32
 - Panel version: 0.9.17

**Comment by nwg-piotr** [comment]
We need better steps to reproduce, as I've been running the panel for 4 hours now and the taskbar module still works. Could you try running the panel from terminal and observe if any error message appears?

**Comment by kuba3351** [comment]
I ran nwg-panel from the terminal and the issue occured, there is a Python stacktrace appeared on the terminal:

```
Exception in thread Thread-11 (hypr_watcher):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/nwg_panel/main.py", line 220, in hypr_watcher
    monitors, workspaces, clients, activewindow = h_modules_get_all()
                                                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 826, in h_modules_get_all
    return h_list_monitors(), h_list_workspaces(), h_list_clients(), h_get_activewindow()
                                                                     ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 817, in h_get_activewindow
    reply = hyprctl("j/activewindow")
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 776, in hyprctl
    s.send(cmd.encode("utf-8"))
BrokenPipeError: [Errno 32] Przerwany potok
```

**Comment by nwg-piotr** [comment]
Closing in hope for it to be fixed. Please re-open if I'm wrong.
