### ISSUE TITLE
Add Support For acpilight for brightness control

### ISSUE THREAD

**Issue by dacyberduck** [nwg-piotr/nwg-panel#279]
Please add support for as brightness controller [acpilight](https://gitlab.com/wavexx/acpilight)

Currently I am using a patch to replace xbacklight (the actual _command_ of acpilight) with light. I would appreciate if acpilight support is added by default.

**Comment by nwg-piotr** [comment]
Doesn't `light` work for you? Possibly you just need to find the proper backlight device?

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/2a28efed-ce14-4a6d-a044-d68793908d06)

**Comment by dacyberduck** [comment]
I am sure light works fine. But xbacklight being a popular brightness contrtroller, should be present.

**Comment by nwg-piotr** [comment]
We already support 2 popular controllers. No way to please everyone.
