### ISSUE TITLE
[BUG] nwg-panel fails to start

### ISSUE THREAD

**Issue by kanyck** [nwg-piotr/nwg-panel#280]
**Describe the bug**
ValueError: Namespace GtkLayerShell not available, error in main.py line 22

**To Reproduce**
launch nwg-panel

**Desktop (please complete the following information):**
 - Gentoo Linux
 - Hyprland-0.33.1
 - nwg-panel-0.9.19
 - gtk-layer-shell-0.8.1

**Additional context**
I suppose some binding is missing...

**Comment by kanyck** [comment]
Actually, there appeared to be 2 versions of wlroots in the system: one installed normally via portage, another as part of hyprland. Uninstalling the 1-st one solved the issue, closing. Sorry for the false alarm.

**Comment by nwg-piotr** [comment]
Good that you sorted it out.

**Comment by sverona** [comment]
I'm still seeing this error even after removing sway's wlroots and building nwg::guru with USE=hyprland. I'm not much of a Gentoo wizard yet; any clue what might be going on here?

My package loadout is:
- nwg-panel-0.9.34
- hyprland-0.39.1-r3
- gtk-layer-shell-0.8.2
