### ISSUE TITLE
Changing height and width causes crashing

### ISSUE THREAD

**Issue by scrubborn** [nwg-piotr/nwg-panel#283]
When changing window height and window width inside of the panel settings menu, upon saving and restarting I can see that nothing changed. If I check the config file for my preset, '/home/user/.config/nwg-panel/hyprland-2' then I can see under menu-start that the height and width are still set to 0, even after saving from the settings app. I tested padding and it didn't save either, it appears to be this whole menu-start category. Changing other panel settings appears to work, just not for this menu.

If I change the settings in the config file myself for height and width, the menu no longer opens.

**Comment by nwg-piotr** [comment]
![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/be3c675c-0671-46f8-9fb2-dffeb242a1b5)

Alright, I know what's going on: "Window width" and "Window height" fields should not be in the form, as nwg-menu doesn't support neither `-width` nor `-height` argument. My mistake, sorry. I'll delete them at another nwg-panel update.

**Comment by scrubborn** [comment]
Gotcha, so in that case is there a way I can change the size? All the screenshots I've seen for the windows style menu look far larger, or atleast taller than mine.

**Comment by nwg-piotr** [comment]
The height depends on the content. The more items inside the menu, the taller it gets. If you only care about aesthetics, just pin up a few apps.

![image](https://github.com/nwg-piotr/nwg-panel/assets/20579136/51db9e5c-a86b-465d-990b-c7507fe21f12)

**Comment by scrubborn** [comment]
Cool, makes sense. Thanks for the help.

**Comment by nwg-piotr** [comment]
You're welcome. I hardly ever use nwg-menu myself, so it looks kind of abandoned. ;)

**Comment by nwg-piotr** [comment]
Nonexistent settings removed on Master.
