### ISSUE TITLE
[BUG] Opens controls menu when clicking tray icons and clipboard manager

### ISSUE THREAD

**Issue by mohammedbilalns** [nwg-piotr/nwg-panel#288]
**Describe the bug**
When clicking tray icons or clipboard manager controls menu shows instead of clicked menus

**To Reproduce**
click the tray icons 

**Expected behavior**
opens icon menu 

**Desktop (please complete the following information):**
 - Linux distribution - Arch 
 - hyprland version  - 0.37.1-1
 -  - Panel version - 0.9.26-1

**Comment by nwg-piotr** [comment]
This is a Hyprland bug (or a feature). I tried to find a workaround, but to no avail so far. It never happens on sway.

**Comment by nwg-piotr** [comment]
It seems I've found the culprit: buggy `on-button-press` event in GTK3. Replacing it w/ `on-button-release` should help.

**Comment by nwg-piotr** [comment]
Fixed in https://github.com/nwg-piotr/nwg-panel/releases/tag/v0.9.27
