### ISSUE TITLE
Hyprland Commit #a5a6480 Breaks NWG-PANEL

### ISSUE THREAD

**Issue by frkli1965** [nwg-piotr/nwg-panel#290]
**Describe the bug**
Hyprland commit #a5a6480 appears to have broken nwg-panel in that hyprland-workspaces and hyprland-taskbar can no longer be loaded.

**To Reproduce**
Build and install hyprland-git with commit #a5a6480 included and restart Hyprland.

**Expected behavior**
 hyprland-workspaces and hyprland-taskbar should be loaded into nwg-panels and operable.

**Desktop (please complete the following information):**
 - Linux distribution:- Arch
 - Hyprland version:- latest git
 - Panel version:- 0.9.28

**Additional context**
I am certain that the stated commit above is responsible since rolling back to the previous Hyprland commit #d20ee31 results in nwg-panel working as expected.

The offending commit's (#a5a6480) description reads as follows:-

    core: Move /tmp/hypr to $XDG_RUNTIME_DIR/hypr (#5788)

    Moves the directory containing sockets and logs.
    Also restructures lockfiles a bit.

    For consumers, check if `$XDG_RUNTIME_DIR/hypr` exists. If so, use it. If not, use the old `/tmp/hypr`.

**Comment by nwg-piotr** [comment]
Thank you. I'll take a closer look at the issue tomorrow.

**Comment by frkli1965** [comment]
Many thanks... :-)

Love the project btw, far superior to the Waybar!

**Comment by nwg-piotr** [comment]
Thanks again! It should be easy to fix, but the alarm clock is going to ring in 4 hours, and I'm not even in bed yet. :)
