### ISSUE TITLE
[BUG] RPM lint issue ambiguous python shebang

### ISSUE THREAD

**Issue by tim77** [nwg-piotr/nwg-panel#295]
**Describe the bug**
In last `v0.9.28` was added airplane-mode indicator script. It have minor issue which RPM linter consider as ERROR.

```
*** ERROR: ambiguous python shebang in /usr/lib/python3.12/site-packages/nwg_panel/executors/airplane_mode.py: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
```

**Expected behavior**
Satisfied linter.

**Desktop (please complete the following information):**
 - Linux distribution: Fedora
 - Panel version `0.9.28`

**Additional context**
Some minor warnings also could be fixed/improved:

```
mangling shebang in /usr/lib/python3.12/site-packages/nwg_panel/executors/au.sh from /usr/bin/env bash to #!/usr/bin/bash
mangling shebang in /usr/lib/python3.12/site-packages/nwg_panel/executors/check-notifications from /bin/bash to #!/usr/bin/bash
mangling shebang in /usr/lib/python3.12/site-packages/nwg_panel/executors/github.sh from /bin/bash to #!/usr/bin/bash
*** WARNING: ./usr/share/applications/nwg-panel-config.desktop is executable but has no shebang, removing executable bit
```

**Comment by tim77** [comment]
Thanks! New version [built](https://koji.fedoraproject.org/koji/packageinfo?packageID=33505) successfully without any build issue.

**Comment by nwg-piotr** [comment]
Great! Thanks for confirmation.
