### ISSUE TITLE
[BUG] Can not start Version 0.9.29

### ISSUE THREAD

**Issue by Schievel1** [nwg-piotr/nwg-panel#296]
**Describe the bug**
When I try to start nwg-panel it will not start and shows the following message:
```
 ➜ nwg-panel
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/nwg-panel", line 5, in <module>
    from nwg_panel.main import main
  File "/usr/lib/python3.11/site-packages/nwg_panel/main.py", line 162
    hypr_dir = f"{os.getenv("XDG_RUNTIME_DIR")}/hypr" if os.path.isdir(
                             ^^^^^^^^^^^^^^^
SyntaxError: f-string: unmatched '('
```

**To Reproduce**
1. start nwg-panel (version 0.9.29)

**Expected behavior**
Nwg-panel starts

**Desktop (please complete the following information):**
 - Gentoo Linux
 - Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460
 - Panel version 0.9.29
 - Python 3.11.9

This also happens with 0.9.28
Also XDG_RUNTIME_DIR exists on my system:
```
➜echo $XDG_RUNTIME_DIR                                            took 61ms
/run/user/1000
```

**Comment by Schievel1** [comment]
Seems like I should migrate to python 3.12

**Comment by nwg-piotr** [comment]
Thanks. I've been trying to understand this bug for 2 days, as it was reported from nwg-displays (I used exactly the same few lines of code), and I'm unable to reproduce it in my environment. Use of f-string was my choice, not a must. Let me take a closer look at it.
