### ISSUE TITLE
Command nwg-panel -v States Wrong NWG-PANEL Version [BUG]

### ISSUE THREAD

**Issue by frkli1965** [nwg-piotr/nwg-panel#298]
**Describe the bug**
nwg-panel -v => nwg-panel version 0.9.28

I have 0.9.31 installed from Github however i.e. latest from the main branch.

Even if I install an explicit tagged release i.e.  'git checkout v0.9.31' the wrong version is given by 'nwg-panel -v'.

**To Reproduce**
Install nwg-panel master branch from Github as prescribed and issue command 'nwg-panel -v' from terminal.

**Expected behavior**
Terminal output should state 'nwg-panel version 0.9.31' surely?

**Desktop (please complete the following information):**
 - Linux distribution: Arch
 - Hyprland version: Latest from main branch (commit #40201a7) at the time of writing.
 - Panel version: 0.9.31 (nwg-panel -v states 0.9.28 however)

**Additional context**
 - Python version: 3.12.3

Downloaded 'setup.py' in root project folder states version='0.9.31' also.

**Comment by nwg-piotr** [comment]
You installed with `sudo ./ install.sh`? You must have multiple `nwg_panel*` dirs in `/usr/lib/python3.12/site-packages/`.

Run: `sudo rm -r /usr/lib/python3.12/site-packages/nwg_panel*`

the use `sudo ./install.sh` again.

**Comment by frkli1965** [comment]
Oops! Indeed I did... :-)
Deleted 28, 29 and 30 and now the correct version comes up.
Didn't have to do that previously however so I assume something has changed.

All the best...

**Comment by nwg-piotr** [comment]
Some time ago the install script would replace the installed version, but it stopped. Probably this could be fixed somehow, but I have no idea.

**Comment by frkli1965** [comment]
Could be resolved with some janky scripting no doubt, risky nevertheless, as the latest could be removed by mistake.
Might be worth mentioning in the readme that manual intervention is required for version bumps however, so that idiots like me, don't keep raising unnecessary issues.

**Comment by nwg-piotr** [comment]
I'm afraid it may be just my lack of knowledge on python. ;)
