### ISSUE TITLE
documentation/template for tray/inner-tray css

### ISSUE THREAD

**Issue by Noctivivans** [nwg-piotr/nwg-panel#299]
Hi,
What are the values supported by tray/inner-tray css files? Also, what is the difference between tray and inner-tray? I've seen nice style.css for panel, but haven't found tray.css/inner-tray.css (or some predefined values in code). I am asking because after one of system updates some of icons became light and as a result are almost invisible (I have custom light theme wrote by myself), and I am trying to figure out if this is my theme issue or something else (invisible icons on screenshot are executor-cpuavg, nextcloud, nm-applet, blueman-applet and button-help):
![swappy-20240507_213158](https://github.com/nwg-piotr/nwg-panel/assets/6827560/7854acfd-7dba-4866-a4ee-9a647a5ddf57)
Thanks in advance and keep up with great work!

**Comment by nwg-piotr** [comment]
Well, I'm not the author of this module, but it seems that the whole Gtk.EventBox has the `root-css-name` name property, and `css-name` belongs to the Gtk.Box inside:

```python
class Tray(Gtk.EventBox):
    def __init__(self, settings, panel_position, icons_path=""):
        self.menu = None
        self.settings = settings
        self.icons_path = icons_path
        Gtk.EventBox.__init__(self)

        check_key(settings, "icon-size", 16)
        check_key(settings, "root-css-name", "tray")
        check_key(settings, "inner-css-name", "inner-tray")
        check_key(settings, "smooth-scrolling-threshold", 0)

        self.set_property("name", settings["root-css-name"])

        self.icon_size = settings["icon-size"]

        self.box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=0)
        if panel_position in ["left", "right"]:
            self.box.set_orientation(Gtk.Orientation.VERTICAL)
        self.box.set_property("name", settings["inner-css-name"])
        self.add(self.box)

        self.items = {}
```

**Comment by nwg-piotr** [comment]
Take a look at the docs here: https://docs.gtk.org/gtk3/css-overview.html
