### ISSUE TITLE
Touchscreen-related problems with controls widget

### ISSUE THREAD

**Issue by brainrom** [nwg-piotr/nwg-panel#3]
When I release a slider on touchscreen, all control panel disappears. Also sometimes I can't tap on some non-sliders menu items. Other widgets works with touchscreen very well.

**Comment by nwg-piotr** [comment]
Well, since there's no way for the panel to check mouse events from outside, w/o adding more dependencies, I decided to close the window on `leave_notify_event`, which is quite convenient if you use the mouse. Possibly this needs a switch to turn on/off in settings. Thanks for pointing it out.

**Comment by brainrom** [comment]
Now it works perfect.

**Comment by nwg-piotr** [comment]
Thanks for testing!

**Comment by nwg-piotr** [comment]
Fixed with #7
