### ISSUE TITLE
[BUG] Unable to change button (playerctl) height with css config

### ISSUE THREAD

**Issue by vitezprchal** [nwg-piotr/nwg-panel#302]
**Describe the bug**
In nwg-panel-config I provided correct name for button ("playerctl-button") however when I try to change height it always stretches to nwg-panel's height even though I changed properties with padding or margin.

**To Reproduce**
1. style.css, change properties

**Expected behavior**
-
**Screenshots**
-
**Desktop (please complete the following information):**
 - Linux distribution: nixos 23.11
 - Sway version `sway -v`
 - Panel version `nwg-panel -v`: nwg-panel version 0.9.15

**Additional context**
-

**Comment by nwg-piotr** [comment]
The "correct" name (CSS ID) for the playerctl button is what you define in the config utility. By default it's "button-custom", unless you redefined the name.

![obraz](https://github.com/nwg-piotr/nwg-panel/assets/20579136/20727b4f-e16d-4cd8-adf5-e344138950cf)
