### ISSUE TITLE
[BUG] Hyprland workspace indicator not updating when empty

### ISSUE THREAD

**Issue by Visual-Dawg** [nwg-piotr/nwg-panel#310]
**Describe the bug**
The Hyprland workspace indicator does not update when switching to an empty workspace until it is not empty anymore.
Then it will work as expected for a bit for this workspace and then it will stop updating again.

**To Reproduce**
Switch to an empty workspace on Hyprland.

**Expected behavior**
The indicator should update to its active state.

**Screenshots**
I am on workspace 3 here:
![image](https://github.com/nwg-piotr/nwg-panel/assets/28539403/e402f5af-0886-49b5-908d-bdc92247db6d)

**Desktop (please complete the following information):**
 - EndeavourOs
 - Hyprland Git 
 - 0.9.34

**Comment by ser** [comment]
I can confirm the bug.

**Comment by nwg-piotr** [comment]
When the module was first written, `hyprctl activeworkspace` was not yet a thing. I'll use it now.
