### ISSUE TITLE
Add class to non-empty Hyprland workspace indicator

### ISSUE THREAD

**Issue by Visual-Dawg** [nwg-piotr/nwg-panel#311]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to visually distinguish workspaces by color.
It is limited to adding a dot at the end of the name, but I want to try out indicators without labels, and only colors.

**Describe the solution you'd like**
Adding a css class like `.non-empty` to the indicators.

**Comment by nwg-piotr** [comment]
I can only add a CSS ID to the label, not the surrounding event box, as it's already taken there, to indicate the focused workspace.

![obraz](https://github.com/user-attachments/assets/dd6746b3-9cb6-4467-bd36-ce2a58cc2752)

**Comment by nwg-piotr** [comment]
It should work in both sway and Hyprland workspaces module now.
