### ISSUE TITLE
[BUG] brightness widget doesn't update based hyprland keybindings

### ISSUE THREAD

**Issue by nergdron** [nwg-piotr/nwg-panel#319]
**Describe the bug**
I've got a hyprland keybinding config that adjusts the brightness of my laptop monitor using `brightnessctl`, but I've noticed the brightness widget in my top `nwg-panel` never seems to pick up these changes caused by something external to it.

it's doubly odd because running the same commands in my shell *does* result in the widget picking it up, so there's probably some interaction here that I don't understand. no clue why running commands in a terminal would produce different results than those run directly by hyprland.

**To Reproduce**
1. set a hyprland key binding to `brightnessctl set 5%-`
2. press the key you bound
3. see that the brightness of your display decreases, but the brightness widget doesn't get updated with the new value

**Expected behavior**
expect the state of the widget to sync with the screen state, like it does when running `brightnessctl` from a terminal.

**Desktop (please complete the following information):**
 - EndeavourOS (arch variant)
 - hyprland 0.43.0-1
 - nwg-panel version 0.9.39

**Comment by nwg-piotr** [comment]
Can't confirm. Works as expected on my side.
