### ISSUE TITLE
[BUG] Systray applet's tooltip are not dynamically resfreshed / udpated

### ISSUE THREAD

**Issue by Antiz96** [nwg-piotr/nwg-panel#320]
**Describe the bug**

When a systray applet gets its tooltip updated, it won't be updated / refreshed dynamically in `nwg-panel` until you reload it (e.g. with `nwg-panel -sigdwl 1`).

**To Reproduce**

1. Launch any systray applet
2. Update its tooltip text (see **Additional context**)
3. Hover your mouse over the systray icon and see that the tooltip hasn't been updated / refreshed accordingly
4. Run `nwg-panel -sigdwl 1` and see that the tooltip gets updated

**Expected behavior**

Systray applet's tooltip to be dynamically updated / refreshed (like it does in e.g. `xfce4-panel`)

**Screenshots**

I can record a video if it helps, just tell me :)

**Desktop (please complete the following information):**

 - Linux distribution: Arch Linux
 - Sway version `sway version 1.9`
 - Panel version `nwg-panel version 0.9.39`

**Additional context**

I'm dynamically updating / modifying the tooltip of the systray applet for my `arch-update` app to include the list of pending updates (for the context, this is done by retrieving the related info from a file thanks to a python 'file watcher' directive, see changes made to the `src/lib/tray.py` file in  https://github.com/Antiz96/arch-update/pull/257). The idea is that users can see the list of pending updates by simply hovering their mouse on the systray icon.

However, it doesn't work in `nwg-panel` as the tooltip is not automatically refreshed / updated, which forces to reload the panel (e.g. with `nwg-panel -sigdwl 1`) to get "updated" tooltip. It works in other panels though, like `xfce4-panel` for instance.

I'm aware that this might be a bit of an unconventional way to use a tooltip but I'm still trying my luck in case this is "fixable" :smile: 

I remain available if you need any more information!

**Comment by nwg-piotr** [comment]
I'd need to set up some testing environment to deal with this issue. Let me think.

**Comment by Antiz96** [comment]
Sure no problem.

If it helps, I can guide you through a way to install & set up Arch-Update and to easily generate tooltip changes for its systray in your testing environment as a test case. Let me know if needed :)

**Comment by nwg-piotr** [comment]
It would be not bad. I'd be sure I'm working on the proper issue. :D

**Comment by Antiz96** [comment]
1 - Install the [arch-update AUR package](https://aur.archlinux.org/packages/arch-update)

2 - Assuming your test env will be using Sway / Nwg-shell: add the `arch-update --tray` command to your sway config to auto-start the systray at boot (you might eventually need to adding a short `sleep` beforehand for it to work properly, e.g. `sleep 3 && arch-update --tray`). 
If your test env is using a desktop environment instead, you can run the `arch-update --tray --enable` command to add the tray into XDG autostart instead.

3 - Install `fastfetch` (random pick, will be used to trigger updates and update the tooltip accordingly): `sudo pacman -S fastfetch`

4 - Download an earlier version of fastfetch from Arch's archives: `curl https://archive.archlinux.org/packages/f/fastfetch/fastfetch-2.25.0-1-x86_64.pkg.tar.zst -O`

5 - Downgrade to the earlier version of fastfetch downloaded above: `sudo pacman -U fastfetch-2.25.0-1-x86_64.pkg.tar.zst` and then right click on the Arch-Update systray icon and click on "Check for updates":

![2024-10-01_09-05](https://github.com/user-attachments/assets/c7d9d4b9-031f-4191-8f3b-4007bb2b6955)

This will generate a new update for your system and trigger a tooltip update accordingly, like so:

![2024-10-01_01-51](https://github.com/user-attachments/assets/34cd5c76-39fe-4e1c-adb3-ce0839971ea6)

6 - You can then left click the systray applet to update your system via Arch-Update (you can answer "Y"es to all questions). This will trigger another tooltip update accordingly, like so:

![2024-10-01_01-49](https://github.com/user-attachments/assets/2abda97b-6415-4c73-a4ea-a9a6f36eb494)

You should see that you need to reload `nwg-panel` (e.g. with `nwg-panel -sigdwl 1`) to get the tooltip updated (while on other panel like `xfce4-panel` for instance, it is updated in real time).

You can repeat steps 5 and 6 as much as you need to generate tooltips updates :wink: 

Hopefully this is clear enough :sweat_smile: 
Let me know if not :)

**Comment by nwg-piotr** [comment]
LOL, I was just about to write a python script to create an icon and update the tooltip text once a second. :rofl: Either way, this needs to wait till the evening, as I'm leaving the office in 20 minutes.

**Comment by Antiz96** [comment]
> LOL, I was just about to write a python script to create an icon and update the tooltip text once a second. 🤣

Well, sure that would work lol. Whatever feels easier to you :rofl: 
At least you know in which context I'm using this now :laughing: 

>  Either way, this needs to wait till the evening, as I'm leaving the office in 20 minutes.

Yeah no problem :) Thanks :pray:

**Comment by nwg-piotr** [comment]
Well, if I create a tray icon with [this script](https://gist.github.com/nwg-piotr/731ddb0a7d462a10c3d3758bb01a68e5) (which also updates the title once a second), it seems to work as expected.

https://youtu.be/9WtHkevERTA?si=amtnVJCmLYsT58j-

**Comment by nwg-piotr** [comment]
Actually the script sets the "Title" property, not "Tooltip" / "ToolTip". This may be the difference. See: https://github.com/nwg-piotr/nwg-panel/blob/1673def21826e89172d64b483d6624fa57226c81/nwg_panel/modules/sni_system_tray/tray.py#L171

I'll try with your use case later tonight.

**Comment by nwg-piotr** [comment]
I end up in something like this:

![image](https://github.com/user-attachments/assets/b3d1a668-8ca5-4414-a675-3103b8a0a056)

**Comment by nwg-piotr** [comment]
It works well now.

**Comment by Antiz96** [comment]
I confirm it works as intended with `v0.9.40`! Thanks a lot :D

**Comment by nwg-piotr** [comment]
A couple of lines of code were missing. It took time to find it, as it's not my code. :)
