### ISSUE TITLE
[BUG] Incorrect current workspace highlight

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/nwg-panel#321]
**Describe the bug**
[x] = highligthed workspace
. = not empty workspace
"number" = empty workspace

MOVING a window from workspace [1.] to 2 will not refresh the current workspace and if it isn't empty.

**To Reproduce**
1. Create any window in workspace [1.]
2. Move window to workspace 2
3. See the panel display the current workspace as [1.] incorrectly instead of [2.]

**Expected behavior**
The panel should highlight the changed workspace after the MOVING window action

**Desktop (please complete the following information):**
 - Arch linux x86_64; Kernel: 6.11.1-arch1-1; Hyperland: v0.43.0
 - nwg-panel version 0.9.40

**Additional context**
The same issue happens if while in the special workspace you SWITCH workspaces. Is possible to see the workspace switching but the highlighted workspace does not update until you close the special workspace.

**Comment by nwg-piotr** [comment]
The above commit seems to fix the issue on my side. Will test it better later tonight.

**Comment by nwg-piotr** [comment]
I think we need to rework and a bit simplify the `hypr_watcher` function.
