### ISSUE TITLE
Some features I would like to see

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/nwg-panel#322]
**Is your feature request related to a problem? Please describe.**
Firstly, thanks for sharing this amazing tool. Here are some features I'm missing and would love to see implemented: 

1.   working media controls (sound mute, (de/in)crease volume) 
2.   keybindings config GUI interface  
3.   in memory module: set the icon to the right of the values and display  RAM as GiB
4.   copy the system info to clipboard

**Describe the solution you'd like**
1. Does not work with the panel by default, need manual binding through hyprland.conf. Ideally with system notification and audio feedback
2. A panel where the user could edit nwg-panel default bindings
3. Place the icon to the right so that it follows the same pattern as the CPU module (or the other way around) ![a](https://github.com/user-attachments/assets/7148ff49-d643-4a11-9668-9733e32714fc) and GiB so it takes less space from the panel
4. So its easier to share your system info with others

**Comment by nwg-piotr** [comment]
1. You got it.

![obraz](https://github.com/user-attachments/assets/454766c2-cbaf-498c-99b9-c10a373e2bb9)

2. nwg-panel uses no key bindings.
3. You got it.

![obraz](https://github.com/user-attachments/assets/a51ee65c-2df5-4435-8d31-325059ed621d)
4. There are plenty of ways you can achieve this. No need to add yet another one.

**Comment by hecto600** [comment]
Sorry for the confusion, I think the features I'm talking is more nwg-shell related 
1. I meant for the keyboard media keys XF86AudioMute, mute ain't working, I manually add to hyprland.conf as bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
3. Thanks
4.  Indeed. I use fastfetch myself now.  With kde options: ![2024-10-04-070013_hypr_screenshot](https://github.com/user-attachments/assets/313c23ef-9d66-4bb8-aef1-e4fd6b60ab2f) 

I could highlight the info with the mouse and copy the line info as one would expect. But the text in nwg System info is not selectable. 

PS: I noticed when I press the System info option the program freezes for a little while

**Comment by nwg-piotr** [comment]
> I meant for the keyboard media keys like XF86AudioMute, mute ain't working, I manually add to hyprland.conf as bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

Of course it could be added to default configs. I didn't do so, since I don't use these keys myself. Possibly I'll add them one day.

> Actually I could add a button to copy all the info to the clipboard. I'll be working on nwg-shell-config this weekend. Hopefully I won't forget about it. :)

> I noticed when I press the System info option the program freezes for a little while

This tab gathers all the info at every usage, and it takes time.
