### ISSUE TITLE
Output by name

### ISSUE THREAD

**Issue by baitmooth** [nwg-piotr/nwg-panel#325]
**Is your feature request related to a problem? Please describe.**
I have a laptop with docking station which is not always connected. When I reconnect to it the external monitors may change their names, e.g. from DP-3 and DP-4 to DP-5 and DP-6. This leads to my panels not showing up on the external monitors. My workaround is to open 'nwg-panel Settings' edit the output settings and apply. 

**Describe the solution you'd like**
Since the names stay the same it would nice to be able to use 'BNQ BenQ FP73G 0x00001D4F' instead of 'DP-3'.

**Describe alternatives you've considered**
Apart from my workaround and the solution I didn't come up with any.

**Additional context**
`swaymsg -t get_outputs`
```Output eDP-1 'AU Optronics 0x133D Unknown' (focused)
 Current mode: 1920x1080 @ 60.049 Hz
  Power: on
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1920x1080 @ 60.049 Hz

Output DP-5 'BNQ BenQ FP73G 0x00001D4F'
  Current mode: 1280x1024 @ 75.025 Hz
  Power: on
  Position: 1920,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 6
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1280x1024 @ 60.020 Hz
…

Output DP-6 'Eizo Nanao Corporation L997 22589035'
  Current mode: 1600x1200 @ 60.000 Hz
  Power: on
  Position: -1200,-900
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: 270
  Workspace: 9
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    1600x1200 @ 60.000 Hz
 …
```

**Comment by nwg-piotr** [comment]
Yes, I was too lazy to do it for a long time. :)

It will look something like this:

![obraz](https://github.com/user-attachments/assets/f7b01e60-c0b9-4bdb-a487-3f441d48e2f0)

and you will be able to select either an output name or a monitor description. Selection of one of them clears the other.

This already works for me, but it's a massive change and I still have to go through a lot of code.

**Comment by baitmooth** [comment]
Okay. I'll just wait then. 
Thanks for this project anyway <3

**Comment by baitmooth** [comment]
That was faster than expected, and works perfectly.
Thanks a lot <3
