### ISSUE TITLE
[BUG] incorrect parameters in start menu config causes silent fail/lockup

### ISSUE THREAD

**Issue by Noctivivans** [nwg-piotr/nwg-panel#326]
**Describe the bug**
If you set incorrect command as screen lock command for MenuStart plugin, the menu becomes inactive (clicking on icon does not open it)

**To Reproduce**
1. open nwg-panel-config
2. Go to "Menu Start" configuration section
3. Set "screen lock command" to e.g. `gtklock --time-format %H:%M:%S -S -H -T 10` (exact command I noticed causing trouble)
4. apply/restart panels config
5. now clicking start menu does not open it

**Expected behavior**
sample solutions:
1. silent fail, but just the screen lock button becomes inactive (instead of whole start menu)
2. visible error message/warning while saving configuration

**Screenshots**
![image](https://github.com/user-attachments/assets/693bc954-e43b-452f-9f56-98c08f2d1f7f)

**Desktop (please complete the following information):**
 - Archlinux
 - Sway version 1.9
 - Panel version  0.9.41

**Additional context**
I was trying to replicate screen lock configuration from nwg-shell options (by the way, option for syncing them would be nice feature to have)
I think that bug is quite new, as I didn't change lock screen command for long time, and start menu used to work before

**Comment by nwg-piotr** [comment]
Do you have 'Run through compositor' in panel -> common settings checked?

![obraz](https://github.com/user-attachments/assets/d016ec39-4092-4833-be9f-6289d2cafba1)

**Comment by nwg-piotr** [comment]
The menu button is just a panel button, it exists even if you attach a wrong command to it. It just won't execute the command, when clicked. This is not a bug, just users typo.

**Comment by nwg-piotr** [comment]
Sorry, I misunderstood your issue at first glance. Will try and learn what's going on.

**Comment by nwg-piotr** [comment]
I'm not sure to which extent it's going to help, but seems to work on my side.

**Comment by Noctivivans** [comment]
Works for me too, thanks :)
