### ISSUE TITLE
[BUG] Buttons unresponsive with version 0.9.47

### ISSUE THREAD

**Issue by pearcep6517** [nwg-piotr/nwg-panel#337]
**Describe the bug**
Buttons inoperative. Errors...

File "/usr/lib/python3.12/site-packages/nwg_panel/modules/custom_button.py", line 58, in on_click
    cmd = cmd_through_compositor(cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/nwg_panel/tools.py", line 933, in cmd_through_compositor
    if "miracle-wm" in os.getenv("XDG_SESSION_DESKTOP"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**To Reproduce**

Upgrade to version 0.9.47

**Expected behavior**

Normal button operation.

**Screenshots**

**Desktop (please complete the following information):**
 - Linux distribution Artix (Arch)
 - Sway version `sway -v`  sway version 1.9
 - Panel version `nwg-panel -v`  0.9.47
 - Python 3.12.7

**Additional context
**warning: nwg-panel: ignoring package upgrade (0.9.45-1 => 0.9.47-1)

**Comment by pearcep6517** [comment]
Ok, sorted out with...
export XDG_SESSION_DESKTOP=sway

**Comment by nwg-piotr** [comment]
OK, but it shouldn't work like this. I'll fix it.
