### ISSUE TITLE
[BUG] nwg-panel requires restart to show panel on all outputs

### ISSUE THREAD

**Issue by JSGRD22** [nwg-piotr/nwg-panel#344]
**Describe the bug**
When a panel is set to "all outputs" and started, and a new monitor is then connected, nwg-panel has to be restarted before the panel shows on the new monitor.

**To Reproduce**
1. Set panel to "all outputs"
2. Connect a new output
3. Panel does not show on new output
4. Restart nwg-panel
5. Panel now shows on new output

**Expected behavior**
nwg-panel updates to show panel on all outputs immediately upon a new connection.

**Desktop (please complete the following information):**
 - Fedora Linux 41 (Sway Atomic) x86_64
 - Hyprland v0.44.1
 - nwg-panel version 0.9.49

**Comment by nwg-piotr** [comment]
Panel instances are being created on startup. There's no way to do what you want.

**Comment by JSGRD22** [comment]
Very well, it isn't hard to script either.
In case anyone else is looking for this, here is a script to restart nwg-panel when a monitor is connected (or more generally when the monitor connections are changed):
```bash
#!/bin/bash

restart_nwg_panel() {
    pkill nwg-panel
    sleep 0.5
    nwg-panel &
}

udevadm monitor --udev --subsystem-match=drm | while read -r line; do
    if echo "$line" | grep -q "change"; then
        restart_nwg_panel
    fi
done
```

**Comment by nwg-piotr** [comment]
To restart nwg-panel, you just need to run the command. It will kill the currently running instance.

**Comment by JSGRD22** [comment]
Good to know, thank you

**Comment by andi242** [comment]
> Very well, it isn't hard to script either. In case anyone else is looking for this, here is a script to restart nwg-panel when a monitor is connected (or more generally when the monitor connections are changed):

thank you! that helped with wayland issues I had using eww.
