### ISSUE TITLE
Add support for hyprland/submap

### ISSUE THREAD

**Issue by JSGRD22** [nwg-piotr/nwg-panel#345]
**Is your feature request related to a problem? Please describe.**
Currently, there is a “sway mode” module for panels that show when sway is in a specific mode, in particular the “resize” mode. Hyprland has a similar feature known as “submaps”. Waybar has support for them, but nwg-panels appears to have no such module.

**Describe the solution you'd like**
A simple module called hyprland submap as a hyprland counterpart to sway mode. It would be particularly helpful when, for example, a submap for resizing windows is activated.

**Comment by nwg-piotr** [comment]
Seems to work well, but needs some testing.

**Comment by nwg-piotr** [comment]
Released in v0.9.56.
