### ISSUE TITLE
[BUG] Controls window extra separator

### ISSUE THREAD

**Issue by IceDBorn** [nwg-piotr/nwg-panel#347]
**Describe the bug**
When the controls window does not have the battery module enabled, there's empty space between 2 line separators.

**To Reproduce**
1. Make sure the controls window does not have the battery module enabled
2. Enable controls window
3. See error

**Expected behavior**
When the battery module is disabled, there should be no line separators or any extra space.

**Screenshots**
![image](https://github.com/user-attachments/assets/c0105fad-2660-4d66-9059-5b0d6fcb259c)

**Desktop (please complete the following information):**
 - NixOS
 - Hyprland version `0.45.0`
 - Panel version `0.9.48`

**Comment by nwg-piotr** [comment]
Well, this menu usually contains more than just batter. I haven't yet seen it totally empty. :D

![obraz](https://github.com/user-attachments/assets/ee1027a7-4e32-4f46-b529-9afbc6bebdb8)

**Comment by nwg-piotr** [comment]
The above should help.
