### ISSUE TITLE
Add option to add new tray items to the left

### ISSUE THREAD

**Issue by JSGRD22** [nwg-piotr/nwg-panel#351]
**Is your feature request related to a problem? Please describe.**
New tray icons appear on the right. One thing I like about nwg-panel over waybar is that the order of the icons is very consistent every time, with network/fcitx/bluetooth arranged neatly on the right side, which is great because I have my tray on the right. However, when a new tray icon is added, it is also added to the right, which causes a minor annoyance.

**Describe the solution you'd like**
Add an option to append new tray icons to the left instead of the right. Waybar has such a feature.
(Additionally, it would be nice if we could demand the tray lock certain icons in certain positions but that might be harder to implement.)

**Comment by nwg-piotr** [comment]
Done. I'll release soon, need some time to test other changes.
