### ISSUE TITLE
[BUG] the actual value of the keyboard layout isnt shown

### ISSUE THREAD

**Issue by m54c1** [nwg-piotr/nwg-panel#352]
The keyboard layout does not change correctly in nwg-panel, even though it works fine in waybar. The layout remains incorrect even when specifying the keyboard by its identifier from swaymsg get_inputs. The keylayout file simply reads the current value from swaymsg.

Simply add several languages in the sway config and add a keyboard layout switcher in nwg-panel.

**Expected behavior**
i expected that everything would change correctly after changing the active keyboard layout

[2024-11-24 01-31-06.webm](https://github.com/user-attachments/assets/8fd0659e-23f9-4752-a33f-3d8b36876696)

 - Linux distribution - arch
 - Sway version - swayfx version 0.4-5f42307 (Sep 26 2024, branch 'master') (based on sway 1.9.0)
 - Panel version - nwg-panel version 0.9.51

**Comment by nwg-piotr** [comment]
No idea what you did to your config, but it works perfectly well for me.

![obraz](https://github.com/user-attachments/assets/a8eecbed-561d-411e-bd22-e61bc2f2a33f)

**Comment by m54c1** [comment]
The problem is that the keyboard layout changes normally through this switch, but when you invoke the language switch using the hotkey defined in the config, nothing changes on the panel. The change is reflected in the waybar, but not here. I don't know how to display my script on the panel. If needed, here is my bash script, and I would appreciate any help in getting it to show on the panel.

https://pastebin.com/ZvV8BH5S

**Comment by nwg-piotr** [comment]
The script has no refresh interval in order not to add to the CPU load. After all it could be refreshed on a signal, but I  expected users just to use the panel UI to switch layouts.

**Comment by m54c1** [comment]
We didn't understand each other. It is fundamentally important for me to change the keyboard layout using hotkeys and at the same time see the current keyboard layout on the panel. I can't do this here, and the question arises: how can I display the name of the language I will be typing in on the panel?

**Comment by nwg-piotr** [comment]
What you need is an executor. You could refresh in a time interval or on a signal.
