### ISSUE TITLE
[BUG] Hyprland workspaces not showing.

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/nwg-panel#353]
**Describe the bug**
It is not displaying the workspace numbers, now it only shows the focused window text.
I did see #338 in the releases note changes about the workspaces but couldn't find the mentioned button.

**Desktop (please complete the following information):**
 - Arch linux
 - sway version 1.10
 - nwg-panel version 0.9.51

**Comment by nwg-piotr** [comment]
My bad, I left the default False value in the panel. Switch it here:

![obraz](https://github.com/user-attachments/assets/907f1595-6192-46e0-ba16-ecb958aae1e2)
