### ISSUE TITLE
[BUG] New glib2 release 2.82.3 breaks systray

### ISSUE THREAD

**Issue by Antiz96** [nwg-piotr/nwg-panel#358]
**Describe the bug**

Upgrading to glib2 2.82.3-1 on Arch Linux breaks systray in nwg-panel.

**To Reproduce**
1. Update to glib2 2.82.3-1
2. Restart nwg-panel (`nwg-panel -sigdwl 1`)
3. Systrays do not appear anymore (see logs in additional context)

**Expected behavior**
Systray still working :D

**Desktop (please complete the following information):**
 - Linux distribution: Arch Linux
 - Sway version `sway -v` sway version 1.10
 - Panel version `nwg-panel -v` nwg-panel version 0.9.53

**Additional context**

Logs:

```
Running instance found, PID 5418, sending SIGINT
Common settings {'restart-on-display': True, 'restart-delay': 500, 'processes-backgroud-only': True, 'processes-own-only': True, 'processes-interval-ms': 2000, 'run-through-compositor': True}
Dependencies check: {'light': False, 'brightnessctl': True, 'ddcutil': False, 'pamixer': False, 'pactl': True, 'playerctl': True, 'wlr-randr': False, 'hyprctl': False, 'upower': False, 'swaync': True, 'python-requests': True}
Running on sway
Outputs: {'DP-2': {'x': 3840, 'y': 0, 'width': 1080, 'height': 1920, 'description': 'Samsung Electric Company LS24AG32x H9JX206899   ', 'monitor': <__gi__.GdkWaylandMonitor object at 0x74a60b669080 (GdkWaylandMonitor at 0x5ff6d17726f0)>}, 'HDMI-A-1': {'x': 0, 'y': 0, 'width': 1920, 'height': 1080, 'description': 'Acer Technologies XV240Y TLVEE0028521', 'monitor': <__gi__.GdkWaylandMonitor object at 0x74a600856c00 (GdkWaylandMonitor at 0x5ff6d1772910)>}, 'DP-1': {'x': 1920, 'y': 0, 'width': 1920, 'height': 1080, 'description': 'Acer Technologies XV240Y TLVEE0028521', 'monitor': <__gi__.GdkWaylandMonitor object at 0x74a600856c40 (GdkWaylandMonitor at 0x5ff6d1772a10)>}}
Descriptions: {'Samsung Electric Company LS24AG32x H9JX206899   ': 'DP-2', 'Acer Technologies XV240Y TLVEE0028521': 'DP-1'}
left box created
center box created
right box created
Panel 'panel-top': output: DP-1, monitor: , position: top, layer: bottom, width: 1920, height: 30
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dasbus/client/observer.py", line 88, in _name_appeared_callback
    callback(name_owner, *callback_args)
  File "/usr/lib/python3.12/site-packages/dasbus/client/observer.py", line 230, in _service_name_appeared_callback
    self._enable_service()
  File "/usr/lib/python3.12/site-packages/dasbus/client/observer.py", line 220, in _enable_service
    self._service_available.emit(self)
  File "/usr/lib/python3.12/site-packages/dasbus/signal.py", line 53, in emit
    callback(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/nwg_panel/modules/sni_system_tray/host.py", line 62, in watcher_available_handler
    for item in self.watcher_proxy.RegisteredStatusNotifierItems:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dasbus/client/proxy.py", line 164, in __getattr__
    return member.get()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dasbus/client/property.py", line 43, in get
    return self.__get__(None, None)  # pylint: disable=unnecessary-dunder-call
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dasbus/client/property.py", line 54, in __get__
    return self._getter()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 382, in _get_property_value
    variant = self._call_method(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 450, in _call_method
    return self._get_method_reply(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
    return self._handle_method_error(error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
    raise exception from None
dasbus.error.DBusError: Remote peer disconnected
```

I remain available if needed :)

**Comment by Antiz96** [comment]
Here are the release note for glib2 2.82.3 (if that helps): https://gitlab.gnome.org/GNOME/glib/-/releases/2.82.3

**Comment by frkli1965** [comment]
Can confirm the same for Arch w/ Hyprland also...

**Comment by frkli1965** [comment]
As a temporary workaround:-

1) Add the following to the IgnorePkg line in /etc/pacman.conf i.e.

IgnorePkg  = glib2 glib2-devel glib2-docs

2) Downgrade the three glib packages to their previous versions  as follows:-

sudo pacman -U https://archive.archlinux.org/packages/g/glib2/glib2-2.82.2-2-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/g/glib2-devel/glib2-devel-2.82.2-2-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/g/glib2-docs/glib2-docs-2.82.2-2-x86_64.pkg.tar.zst

Reboot...

3) Remove the glib2 glib2-devel glib2-docs packages from the IgnorePkg line in /etc/pacman.conf when the fix is in obviously so that they can be upgraded in due course.

**Comment by nwg-piotr** [comment]
Downgrading glib2 helps.

To me it doesn't look like something possible to fix on the nwg-panel Tray module level.

**Comment by Antiz96** [comment]
> Downgrading glib2 helps.
> 
> To me it doesn't look like something possible to fix on the nwg-panel Tray module level.

You think it would be a regression at the glib2 level itself?
If so, I can try to bisect it to identify the "offending" commit so it can be reported.

**Comment by nwg-piotr** [comment]
I think so. However, it won't be easy to report, as the exception itself is being thrown from python-dasbus.

**Comment by nwg-piotr** [comment]
Thank you very much!

**Comment by Antiz96** [comment]
Ha, turns out it was already reported upstream apparently: https://gitlab.gnome.org/GNOME/glib/-/issues/3559

**Comment by Antiz96** [comment]
And a potential fix already: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/4427 \o/

I notified the glib2 maintainer on Arch side about it. I'll let you know.

**Comment by nwg-piotr** [comment]
Thank god it's not on my end. I'm always afraid of bug reports from the Tray module, as it's way beyond my skills.

**Comment by Antiz96** [comment]
The glib2 Arch package [has been patched](https://gitlab.archlinux.org/archlinux/packaging/packages/glib2/-/commit/89137ab46f9f2293e571b1173cd5f64a11129278). The issue should be fixed with `glib2 2.82.3-3`.

I'll confirm it as soon as I can.

**Comment by nwg-piotr** [comment]
Fingers crossed for it to help.

**Comment by Antiz96** [comment]
> Fingers crossed for it to help.

It does :)

I can confirm upgrading to `glib2 2.82.3-3` and restarting nwg-panel with `nwg-panel -sigdwl 1` fixes the issue :D

**Comment by nwg-piotr** [comment]
It does, indeed. Great job!

**Comment by nergdron** [comment]
as someone who was affected by this bug but didn't have a lot of time to dig into it, love to see y'all tracking this all the way through in a short period of time. great work, y'all, I appreciate you. :grin:
