### ISSUE TITLE
Laggy and sluggish sliders and animations

### ISSUE THREAD

**Issue by sergeyshadok** [nwg-piotr/nwg-panel#359]
I've just installed nwg-shell on Artix Linux + Hyprland and I'm noticing that nwg-* components have sluggish animations and volume & brightness sliders are very laggy.  Also "appearing" animations of panel menus look like they are rendering at 20-25 fps (not smooth).

Video demonstration of this:

https://github.com/user-attachments/assets/fa978a46-289d-479f-bb99-7569265cf2af

**Comment by nwg-piotr** [comment]
Well, the sliders were not as butter fluent as I thought. I fixed it, release on the way.

**Comment by sergeyshadok** [comment]
Thank you :)
