### ISSUE TITLE
Add CSS elements to Random Wallpaper

### ISSUE THREAD

**Issue by Quasar-0330** [nwg-piotr/nwg-panel#360]
I noticed that when I tried to set the border of Random Wallpaper to be transparent in css, there was no CSS element, so please add one.

Also, swaybg is required to use Random Wallpaper, so please add swaybg to nwg-panel's dependencies.

**Comment by nwg-piotr** [comment]
Use the `menu` selector.

![2024-12-13-003048_hypr_screenshot](https://github.com/user-attachments/assets/4a4e69d5-23a3-44fe-a960-883db4adc42d)

> Also, swaybg is required to use Random Wallpaper, so please add swaybg to nwg-panel's dependencies.

Yes, I should have mentioned this in release notes. @Antiz96, could you, when you have a spare minute?

**Comment by Antiz96** [comment]
> > Also, swaybg is required to use Random Wallpaper, so please add swaybg to nwg-panel's dependencies.
> 
> Yes, I should have mentioned this in release notes. @Antiz96, could you, when you have a spare minute?

Added as an optional dependency :)
See https://gitlab.archlinux.org/archlinux/packaging/packages/nwg-panel/-/commit/7cadaa9422c96a4ab546cf05ceba080d30005650

**Comment by Quasar-0330** [comment]
I don't want to change the border of the menu when clicked, I want to change the border around the Random Wallpaper icon.

![2024-12-13-173142_hyprshot](https://github.com/user-attachments/assets/9104074f-6be4-4db9-9f10-1aedd079b3d1)

**Comment by nwg-piotr** [comment]
Exactly, as the module is inactive by default in nwg-panel installed standalone. In default nwg-shell profiles it's turned on, but we have swaybg already installed. 

Thank you!

**Comment by nwg-piotr** [comment]
> I don't want to change the border of the menu when clicked, I want to change the border around the Random Wallpaper icon.

Ah, ok.
