### ISSUE TITLE
[BUG] Breaking on using a CSS reset block

### ISSUE THREAD

**Issue by msmafra** [nwg-piotr/nwg-panel#368]
**Describe the bug**
nwg-panel breaks when using a CSS reset block. On nwg-drawer (awesome tool), nwg-grid, nwg-bar or nwg-hud it works fine.

**To Reproduce**
1. Add the following to the style.css file
```
* {
    all: unset;
    font-size: 16px;
    font-family: 'Inter Variable', 'Symbols Nerd Font';
    font-feature-settings: '"zero", "tnum", "ss01", "ss02", "ss03", "cv01", "cv05", "cv08", "cv10", "cv11", "cpsp", "case"';
    animation-timing-function: steps(12);
    animation-duration: 0.3s;
    transition: all 0.3s cubic-bezier(0.79, 0.33, 0.14, 0.53);
    border-radius: 0.25rem;
}
```
2. Reload/restart nwg-panel with that modified style.css
3. See the error

**Expected behavior**
To have all feature reset instead of crashing/break/not load.

**Screenshots**
![image](https://github.com/user-attachments/assets/089299bb-f368-44e2-8782-8cdd8918e2ef)

**Desktop (please complete the following information):**
 - Linux distribution
   Fedora Workstation 41
 - Sway version `sway -v` 
   Hyprland 0.46.2
 - Panel version `nwg-panel -v`
   0.9.55 and 0.9.58

**Additional context**
I use this reset for my CSS files for, I think all utilities I'm setting on Hyprland: nwg-drawer, nwg-grid, nwg-bar, nwg-hud, waybar, swaync, wlogout etc.
```
* {
    all: unset;
    font-size: 16px;
    font-family: 'Inter Variable', 'Symbols Nerd Font';
    font-feature-settings: '"zero", "tnum", "ss01", "ss02", "ss03", "cv01", "cv05", "cv08", "cv10", "cv11", "cpsp", "case"';
    animation-timing-function: steps(12);
    animation-duration: 0.3s;
    transition: all 0.3s cubic-bezier(0.79, 0.33, 0.14, 0.53);
    border-radius: 0.25rem;
}
```

**Comment by nwg-piotr** [comment]
Fixing this is definitely out of my range. According to AI, this may be a limitation of GTK's CSS engine in python. How much are you bond to `transition: all 0.3s cubic-bezier(0.79, 0.33, 0.14, 0.53);`? Replacing it with `transition: all 0.3s ease;` prevents the panel from crashing.

**Comment by msmafra** [comment]
> 3s ease

Oh! No problem whatsoever. I thought it was more than that. Didn't even consider that the cubic-bezier could be the culprid.

**Comment by nwg-piotr** [comment]
Very well. Possibly we could submit a bug report to pygobject maintainers, but on Friday evening I'd rather have some beer. ;)

**Comment by msmafra** [comment]
Cheers :beer: ! Thanks!
