### ISSUE TITLE
Make the volume icon scrollable

### ISSUE THREAD

**Issue by therealmate** [nwg-piotr/nwg-panel#372]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it's slightly annoying that i have to click on the volume icon to adjust the volume and not just simply be able to scroll

**Describe the solution you'd like**
If hovering over the volume icon, the panel should allow adjusting the volume (by a configurable amount) by either scrolling up or down

**Comment by nwg-piotr** [comment]
Sorry, we have just one GtkEventBox here. Just click and scroll over a proper Gtk.Scale.
