### ISSUE TITLE
Support system tray

### ISSUE THREAD

**Issue by emmaliddell** [nwg-piotr/nwg-panel#41]
I'd like to be able to fully replace waybar with nwg-panel. One thing preventing me from doing so is a lack of support for displaying system tray icons. 

If you added tray support, that would make nwg-panel a great replacement for other sway panels.

**Comment by nwg-piotr** [comment]
Well, personally I don't miss the tray much, but I was asked to implement it several times. It's quite a lot of difficult code to add, provided that it's doable in python at all. For now the tray, together with the wlr-taskbar, are on TODOs, but with no ETA.

**Comment by asjur** [comment]
This is the only blocker for me. Without systray my workflow is quite hampered. Is there any update to this?

**Comment by nwg-piotr** [comment]
Unfortunately not. I read through the code of existing C++ implementations, and a half of classes / functions used there have no pygobject counterparts. The only tray coded in python I managed to find on GitHub uses tons of own libraries, and is heavily out of date. Writing all the stuff from scratch exceedes my skills, and I don't know if it's even possible.

**Comment by IntinteDAO** [comment]
Well - if sway / waybar is an issue then maybe developing indicators makes sense. I mean something like in Gnome - sound indicator, message indicator etc, something like tray icon, but classic tray icons are mainly for Xorg.

Second thing is support for submenu like in Gnome. And together these two things mostly solve the problem for the user.

![Zrzut ekranu z 2021-06-30 21-52-07](https://user-images.githubusercontent.com/56807194/124022794-94b07180-d9ed-11eb-884c-024cd4c110ab.png)

**Comment by nwg-piotr** [comment]
Take a look at the [Controls](https://github.com/nwg-piotr/nwg-panel/wiki/modules:-Controls) module. Also you may add almost any content as an executor.

**Comment by pocek** [comment]
Have you considered using libdbusmenu-gtk through GI?

I know it's hard to call libdbusmenu actively maintained and the world is going to reinvent stuff once again (see AyatanaIndicators/libayatana-appindicator#22), but it still looks like a viable and relatively quick solution, at least for GTK 3. Paired with some dbus-fu it does a decent job in waybar's sni module. I **hope** I haven't missed something important, because otherwise it looks doable in python (I consider hacking on it).

**Comment by nwg-piotr** [comment]
> waybar's sni module

I read through their code. A half of the classes / methods they use has no counterpart pygobject. Even if it can be done in python, I have absolutely no idea how.

**Comment by pocek** [comment]
Do you mean the `SnWatcher` class and the `sn_*` stuff? These are generated from D-Bus interfaces (introspection XMLs), but instead of generating code we can pick whatever python D-Bus library we like (or even stick with `Gio.DBusProxy`) and go from there. Is there something else that is missing?

**Comment by nwg-piotr** [comment]
I have no experience with D-Bus, except for some watcher example I played with long time ago, out of curiosity. I'm a hobbyist programmer, and implementing systray exceeds my skills. Secondly, I can live perfectly well without it. If the tray is going to appear in the project one day, some commitment from a pro developer is required.

**Comment by nightly-brew** [comment]
@nwg-piotr  I have absolutely no experience on the matter, but I'm willing to start from scratch and try to come up with something working decently, if you don't mind me fiddling with the code.

**Comment by nwg-piotr** [comment]
Thumbs up. I don't really need it personally, but it would be not bad to have it on stock.

**Comment by nightly-brew** [comment]
Small update:
I'm studying dbus since KDE's SNI uses that, but I'm also following closely [the discussion about the new status notifier specification](https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/84).

One major issue with KDE's SNI is that it's not exactly compatible with containerized/sandboxed programs like flatpak ones, which was enough to warrant for a new standard to come out.

Unless the workforce team comes up with a compat layer, we will need to support two or more standards at once.

**Comment by christian-schulze** [comment]
@nightly-brew I've done some initial work on this, with working sni watcher/host and tray module correctly showing icons. Next step is implementing the menu's. Please feel free to continue working on it.

**Comment by nightly-brew** [comment]
Wow thanks!

**Comment by nightly-brew** [comment]
> @nightly-brew I've done some initial work on this, with working sni watcher/host and tray module correctly showing icons. Next step is implementing the menu's. Please feel free to continue working on it. PR here: #87

Thanks!
I'll see what I can do.

**Comment by christian-schulze** [comment]
@nightly-brew the PR has actually progressed very quickly, hopefully will be merged in the next 12 hours

**Comment by nightly-brew** [comment]
Yeah I took a look, you did way more than I could have done in that time, since it's all new stuff to me. gg!
