### ISSUE TITLE
Mirror bars to all outputs

### ISSUE THREAD

**Issue by mjdazz** [nwg-piotr/nwg-panel#48]
I love your panel, thanks for your work! 

I was wondering if it's possible to automatically mirror all bars to all outputs. I sometimes work with two and sometimes with only one screen and I'd like to see the same information all the time without the additional effort of managing multiple bars with the same content.

**Comment by nwg-piotr** [comment]
Thank you! :)

Actually each panel is a separate window, and I have no idea on how to mirror windows at the moment. However, for now, if you don't specify an output, the panel appears on what it detects as primary. Possibly we could start from here, and create identical windows on all outputs if none specified? Just thinking aloud...
