### ISSUE TITLE
SwayTaskbar doesn't show icons for some applications

### ISSUE THREAD

**Issue by CIAvash** [nwg-piotr/nwg-panel#59]
For example Element and Manuskript. Maybe instead of looking at the icon names which are `element` and `manuskript`, the uppercase versions are being used to find icons?

Also if a desktop entry is opened and the icon specified there doesn't exist, taskbar crashes.

**Comment by nwg-piotr** [comment]
> Also if a desktop entry is opened and the icon specified there doesn't exist, taskbar crashes.

Couldn't confirm: it results in 'icon-missing' on my end. Any exact example?

**Comment by CIAvash** [comment]
> > Also if a desktop entry is opened and the icon specified there doesn't exist, taskbar crashes.
> 
> Couldn't confirm: it results in 'icon-missing' on my end. Any exact example?

Sorry, I had to be more specific, the case was an appimage app that created a desktop file with the `Icon=appname.png` field. Having the `.png` or `.svg` extensions(the ones I tried) crashes the taskbar.

**Comment by nwg-piotr** [comment]
Alright, got it. Thanks!

**Comment by nwg-piotr** [comment]
Would you be able to clone and install from the `empty_name` branch, and tell me if it works for you?

**Comment by CIAvash** [comment]
Yeah, everything is working now.

**Comment by nwg-piotr** [comment]
Thanks. I'll merge after I finish fixing one more bug.
