### ISSUE TITLE
Workspaces module - window name length limit isn't respected for floating windows

### ISSUE THREAD

**Issue by tmarkov** [nwg-piotr/nwg-panel#62]
When I open a floating window on sway with a long name, the name on the panel stretches to its full length - and if it's long enough, makes the left side of the panel go "off-screen" to the left of the screen (I have the workspaces module on the left). Everything behaves normally with tiled windows.

**Comment by nwg-piotr** [comment]
This module is still not enough tested, as I don't really use it. Thanks for reporting, I'll take a look at the issue.
