### ISSUE TITLE
Vertical panels.

### ISSUE THREAD

**Issue by Lattyware** [nwg-piotr/nwg-panel#69]
**Is your feature request related to a problem? Please describe.**
It's common to have widescreen monitors where vertical space is much more valuable than horizontal space: I'd rather have 
my panels on the left/right than on the top/bottom for this reason.

**Describe the solution you'd like**
Panels to support left/right positioning, and related left/right anchors for components change to being start/end based on the orientation of the panel.

**Describe alternatives you've considered**
I took a quick look at trying to change the CSS and/or settings to hack this together, but as far as I can tell this requires some more core changes.

**Additional context**
N/a.

**Comment by nwg-piotr** [comment]
Well, at the very beginning I made the assumption that nwg-panel will never support vertical panels, as they make no sense and nobody needs them. This is the case on my triple-headed setup (3 x 1920x1080). Although your explanations to some degree justifies the need of vertical panels, on this stage of development it would be quite a lot of work. Not just the panel displacement, but also all the modules would need to be more or less rewritten. Let me be honest: I'm an after hours developer, working, with hardly any contributors, on the project which contains 8 different programs. Choosing from among the feature request, I give priority to those, that may also be useful to me. I can only promise to take a closer look at it when I have nothing better to do.

**Comment by Lattyware** [comment]
I understand, don't worry—not expecting any magic, just made an issue to show interest. If you are open to it and if/when I have time, I might fork and take a look at making the changes myself, with a view to a PR in the future if it works out.

**Comment by nwg-piotr** [comment]
Why not. All the nwg-shell project needs reliable contributors. For now I'm about to finish the DwlTags module and publish v0.5.0, when tested. Later I'll have to add a feature to nwg-wrapper, which I promised to add a week ago, and finally take some rest from python. Apart from drinking beer over the weekend, I'll need to pay some attention to nwg-menu, written in Go.

**Comment by Ashe** [comment]
I'm interested in this as well. My resolution is 5120x1440, and I have waybar on the right. If it was at the top or bottom, I have a long strip of wasted space. I just gave nwg-panel a go and was in disbelief that it only had top/bottom support - I thought it was my fault I couldn't find the option at first!

Either way, congratulations on making a cool thing :)

**Comment by nwg-piotr** [comment]
Well, not my most wanted feature, but I'll try. Current progress:

![2022-05-31-030642_screenshot](https://user-images.githubusercontent.com/20579136/171073566-f98808d6-2464-4b13-91f4-3147cf22e589.png)
