### ISSUE TITLE
[BUG] Bump version in setup.py

### ISSUE THREAD

**Issue by tim77** [nwg-piotr/nwg-panel#78]
**Describe the bug**
Version v0.5.4 released, but forgot to bump version [here](https://github.com/nwg-piotr/nwg-panel/blob/v0.5.4/setup.py#L11).

**Additional context**
Very minor issue, but i thought worth to notify. Thanks.

**Comment by nwg-piotr** [comment]
Hell, I was doing this slightly in a hurry. Thanks!
