### ISSUE TITLE
Volume indicator: middle click to mute

### ISSUE THREAD

**Issue by TRPB** [nwg-piotr/nwg-panel#80]
This panel is great and minimal, but one feature I had become accustomed to in KDE is the ability to middle click the volume icon to mute. I'd imagine this is fairly easy to implement as the icon already exists and the mute functionality already exists so hopefully a fairly trivial request .

**Comment by nwg-piotr** [comment]
Just click here:

![image](https://user-images.githubusercontent.com/20579136/148660262-4e897fe9-5434-43de-97cf-1a80a39dac9d.png)

**Comment by nwg-piotr** [comment]
Closing in lack of further feedback.
