### ISSUE TITLE
panel does not show up on laptop screen when using "show on all monitors"

### ISSUE THREAD

**Issue by nightly-brew** [nwg-piotr/nwg-panel#81]
**Describe the bug**
Today when starting sway I noticed the panel didn't show up. Initially I though it crashed, but systemctl showed the service to be up and running.
Fiddling with the panel settings I managed to get the panel to show by selecting the specific output of the laptop (eDP-1).
Previously it was setup to show it on all monitors.
Changing it back to "all" hides the panel again.

**To Reproduce**
1. Start nwg-panel
2. Open the panel settings and select a panel
3. On "panel" tab, set Output to "all"
4. Click to apply and restart
5. The panel disappears

**Expected behavior**
The panel shows up on all monitors.

**Desktop (please complete the following information):**
 - Linux distribution: Archlinux (system updated at the time of bug report)
 - Sway version: 1.6.1
 - Panel version: 0.5.6

**Additional context**
This happened when I used the laptop standalone.
Every other day, an external monitor is plugged in.
Previously, the "all" settings worked flawlessly.

I cited systemctl because I run nwg-panel as a systemd user service.

**Comment by nwg-piotr** [comment]
> The panel disappears

On my 3-headed setup it's not true. Kill the panel, start it from the terminal, and show me the output.

**Comment by nwg-piotr** [comment]
OK, got it. In `main.py` line 318 it should be:

```python
if panel["output"] == "All" and len(common.outputs) >= 1:
```
