### ISSUE TITLE
Let user choose which backlight device is controlled by brightness slider

### ISSUE THREAD

**Issue by Redecorating** [nwg-piotr/nwg-panel#83]
**Is your feature request related to a problem? Please describe.**
My computer (an Apple MacBookPro16,1) has two backlight devices:

```shell
$ ls /sys/class/backlight/
acpi_video0  amdgpu_bl0
```

"acpi_video0" is the one that actually controls my display backlight, while "amdgpu_bl0" does nothing. When `nwg-panel` calls `light`, it selects the amd backlight by default, so the brightness slider in my panel's controls menu doesn't do anything.

**Describe the solution you'd like**

I would like some way to set the backlight device that is used so that I can set it to control the "acpi_video0" backlight. This could probably be done by adding a dropdown menu that lets you select from the outputs of 

```shell
$ ls /sys/class/backlight`
acpi_video0 
amdgpu_bl0
```

 If a specific backlight is selected, `-s sysfs/backlight/<SELECTED_BACKLIGHT>` could be added to `light`'s arguments, or `-d <SELECTED_BACKLIGHT>` to `brightnessctl`

This dropdown to select device could be located above "output switcher" and to the right of "Brightness" in this screenshot:
![image](https://user-images.githubusercontent.com/69827514/150741775-6d9dae92-60f2-4209-9a4f-398cd119cb8f.png)

**Describe alternatives you've considered**
Alternatively, the slider in the panel's controls thing could be set up to change the brightness of all display backlights in the system.

**Additional context**

`light` is called to set brightness here in the code https://github.com/nwg-piotr/nwg-panel/blob/97e2cc0ee8e5f050d92a74434978d6bd71496cd2/nwg_panel/tools.py#L432

**Comment by nwg-piotr** [comment]
Of course it could be done, but, if I remember well, selecting a device for `light` (like e.g. `light -A 5 -s sysfs/backlight/amdgpu_bl1` once was enough for it to use the same one in consecutive calls. Maybe I'm wrong. Also: if the `light` package not found, the panel will try the `brightnessctl` command. Have you checked this?

**Comment by Redecorating** [comment]
Both `light` and `brightnessctl` seem to be using `amdgpu_bl0` as the default and they don't seem to store the last used backlight. `light` can store backlight levels in `~/.config/light/` with `light -O`, but I don't think I can set the default device there.

**Comment by nwg-piotr** [comment]
I was just about to start adding the feature you request, but reminded that my machine suffers from the same issue. Have you tried adding the `acpi_backlight=vendor` kernel flag?

**Comment by nwg-piotr** [comment]
What I added should work, but needs to be tested carefully. Could you install from the `light_device` branch and check?

**Comment by Redecorating** [comment]
It ends up setting the brightness correctly, but then it resets it to the brightness that the default backlight has, which I think is because device seems to not be set when get_brightness is called.

```diff
diff --git a/nwg_panel/modules/controls.py b/nwg_panel/modules/controls.py
index 35a96f3..7a35879 100644
--- a/nwg_panel/modules/controls.py
+++ b/nwg_panel/modules/controls.py
@@ -191,7 +191,7 @@ class Controls(Gtk.EventBox):
             self.bt_label.set_text(name)
 
     def update_brightness(self):
-        value = get_brightness()
+        value = get_brightness(device=self.settings["backlight-device"])
         icon_name = bri_icon_name(value)
 
         if icon_name != self.bri_icon_name:
```
this change makes it work perfectly

**Comment by nwg-piotr** [comment]
Thanks! I expected something to be missed, as it was late in the night. I'll add this.
