### ISSUE TITLE
[BUG] backlight control causes flickering of light intensity

### ISSUE THREAD

**Issue by JDPDO** [nwg-piotr/nwg-panel#90]
**Describe the bug**
nwg-panel's backlight control causes flickering of light intensity when mouse hovers panel widget during use of sway's keybindings for brightness control.

**To Reproduce**

1. Setup sway's `bindsym`-directive for brightness control using `light`-command.`
2. Hover control widget.
3. Use keybindings.

**Expected behavior**
Backlight intensity "jumps" sometimes down on going up and reverse.

**Desktop (please complete the following information):**
 - Linux distribution Artix Linux (kernel 5.16.5)
 - Sway version 1.7
 - nwg-panel version 0.6.1

**Additional context**
My bindsym commands are:
```
bindsym XF86MonBrightnessDown exec light -T .5
bindsym XF86MonBrightnessUp exec light -T 2
```

_Volume control should also be affected._

**Comment by JDPDO** [comment]
**Possible solution:** (as I am able to evaluate)

1. Save the last value of [`get_brightness`](https://github.com/nwg-piotr/nwg-panel/blob/3c26c95133ad676ba72b3823ab6811be4a8cb579/nwg_panel/tools.py#L406) in variable.
2. Compare saved value with new call of `get_brightness`. If same exec `set_brightness` else reset slider in method [`set_bri`](https://github.com/nwg-piotr/nwg-panel/blob/3c26c95133ad676ba72b3823ab6811be4a8cb579/nwg_panel/modules/controls.py#L649).

**Comment by nwg-piotr** [comment]
I think it has nothing to do with the panel. On my MSI laptop `XF86MonBrightnessUp` / `Down` keys behave oddly. Sometimes pressing one of them fires both events for `Up` and `Down` key randomly. Try to see what's going on in `wev`. When I attach the backlight control to other keys, everything works as it should. In real life I don't use keys to adjust brightness at all, as I have sliders in the panel.

**Comment by JDPDO** [comment]
I've looked into the key thing. The key events are registered as expected. No keys stumbling around.

**Comment by nwg-piotr** [comment]
OK, I'll take a closer look at it.
