### ISSUE TITLE
[BUG] volume control sets audio volume without beeing actively altert

### ISSUE THREAD

**Issue by JDPDO** [nwg-piotr/nwg-panel#91]
**Describe the bug**
The control widget popup window alters volume when started on hovering with mouse. 

**To Reproduce**
1. Overmodulate Pulseaudio's default sink
2. Only open controls widget popup window by hovering with mouse over widget.
3. Volume is reset to 100% (altert without active intervention)

**Expected behavior**
Don't alter without active user input.

**Desktop (please complete the following information):**

- Linux distribution Artix Linux (kernel 5.16.5)
- Sway version 1.7
- nwg-panel version 0.6.1

**Additional context**

This problem is probably related to #90.

**Comment by nwg-piotr** [comment]
Well, can't reproduce this behaviour in any way....

**Comment by JDPDO** [comment]
![preview_change-vol](https://user-images.githubusercontent.com/11973633/153700497-bd6204b7-81f4-4b35-8c64-fa7b8b934a4f.gif)

> **To Reproduce**
> 
>     1. Overmodulate Pulseaudio's default sink
> 
>     2. Only open controls widget popup window by hovering with mouse over widget.
> 
>     3. Volume is reset to 100% (altert without active intervention)

Tried again: Works not always either. After some experimenting I figured out it works always if the described steps are done after
**(0.)** changing the gui range control and quitting the popup.

**Comment by nwg-piotr** [comment]
I'm trying again and again, but it always works well here...

**Comment by nwg-piotr** [comment]
I've even installed Artix, still to no avail.

**Comment by JDPDO** [comment]
I'll try fixing the bug and do a pull request. But wow, you installed an entire os for bug tracing: you got my respect.
