### ISSUE TITLE
[BUG] Panel is cut off if center section gets "to big"

### ISSUE THREAD

**Issue by JDPDO** [nwg-piotr/nwg-panel#95]
**Describe the bug**
If the middle section of the panel is packed to full, both, the left and right sections are cropped.

**To Reproduce**
Pack the middle section so full its greater than one third of the panel.

**Expected behavior**
If there is space left or right available do not chop the panel.

**Screen record**
![recording0](https://user-images.githubusercontent.com/11973633/155941698-86f9897d-52ca-46fb-9e53-6fae477c6714.gif)

**Desktop (please complete the following information):**
 - Linux distribution Artix Linux (kernel 5.16.11)
 - Sway version 1.7
 - Panel version 0.6.2

**Additional context**
Works even on wide screens (21:9).

**Comment by nwg-piotr** [comment]
If the Center modules are in use, the Left, Center and Right section must be of the same width. Sorry, I see no other way to align Center modules properly. That's why too long content of one section affects other sections. Just avoid long content if you use Center modules.

**Comment by JDPDO** [comment]
I'm doing that :wink:.

But I think the behavior is counterintuitive. I've seen through coincidence the [`set_center_widget`](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Box.html#Gtk.Box.set_center_widget) method in the doc you referenced. Seems to be new, would that method work? I am no familiar with GTK.

Or maybe a dropdown?

**Comment by xircon** [comment]
I have the same problem.  If I set the label parameter of playerctl and workspaces to the lowest it improves.

Could we have label length zero?  and no status labels (e.g. paused)?

**Comment by nwg-piotr** [comment]
> Could we have label length zero? and no status labels (e.g. paused)?

This could be done. But I'll be working on nwg-panel no sooner than in a week. I'm writing in golang at the moment, and switching my brain back and forth python/go is a PITA.

**Comment by xircon** [comment]
:+1:
