### ISSUE TITLE
Systemwide hotkeys

### ISSUE THREAD

**Issue by JDPDO** [nwg-piotr/nwg-panel#96]
**Is your feature request related to a problem? Please describe.**
The `Windows`-Key doesn't work nor is it possible to trigger an event for nwg-panel to open the start menu.

**Describe the solution you'd like**
We need _trigger-commands or -options_.
`swaymsg` like solution with triggers for every panel element to be consistent.

Perhaps `nwg-panel trigger menu_start` and `nwg-panel trigger controls`. Trigger for open, but must not be.

**Describe alternatives you've considered**
A similar solution like before, but one step up. As a _messager_ for nwg-shell. Name could be `nwgmsg` or it could be part of `nwg-shell` command.

**Comment by nwg-piotr** [comment]
Sorry, but gtk-layer-shell only supports keyboard events in exclusive mode. When turned on, it would.

> menu_start 

...is a separate application written in go. The panel only runs it w/ arguments defined in config.py.

We could use signals to trigger some actions, but we have a limited number of signals, and I wanted to save them for future development: triggering module refresh.

**Comment by JDPDO** [comment]
> Sorry, but gtk-layer-shell only supports keyboard events in exclusive mode. When turned on, it would prevent all other apps from interaction with the keyboard.

This makes sense, I did not know. If there would be a  _trigger-command_ it would be possible to `bindsym` the command in the sway, i3 or dwl configs. (hope thats true for dwl too :sweat_smile:)

> Yes. Just run nwg-menu w/ appropriate arguments. See `nwg-menu -h`.

I know, but this way, if the location of the panel and/or button changes you have to change two configurations (once the nwg-panels, second the window managers). What I mean is that the bar knows where the button is and also where the user expects the start menu.
More like a work around, but I think not too spaced out.

> We could use signals to trigger some actions, but we have a limited number of signals, and I wanted to save them for future development: triggering module refresh.

That's not what I ment, but the future use is a neat idea.

**Comment by JDPDO** [comment]
> What I mean is that the bar knows where the button is and also where the user expects the start menu.

To avoid vendor-lock-in there could be position config options for possible other start menu vendors.

**Comment by nwg-piotr** [comment]
The menu start button is nothing but a button. You may add as many other buttons, connected to any other app, as you want.
